### ISSUE TITLE
Error when using water on Chiseled Bit Storage in multiplayer

### ISSUE THREAD

**Issue by gaam24** [ChiselsAndBits/Chisels-and-Bits#1097]
Hi, when I try use water on Chiseled Bit Storage on multiplayer server I got an error, on singleplayer it work fine.

Minecraft: 1.19.2
Fabric: 0.14.19 
Fabric-api: 0.76.0+1.19.2
Chisels & Bits: v1.3.135

Error log:
> `[22:28:44] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@2df428d0, suppressing error
[22:28:44] [Server thread/ERROR]: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.transfer.v1.client.fluid.FluidVariantRenderHandler in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base@17.0.6/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.communi.suggestu.scena.fabric.platform.FabricScenaPlatform.getFluidManager(FabricScenaPlatform.java:63)
	at com.communi.suggestu.scena.core.fluid.IFluidManager.getInstance(IFluidManager.java:25)
	at mod.chiselsandbits.block.entities.BitStorageBlockEntity.addHeldBits(BitStorageBlockEntity.java:195)
	at mod.chiselsandbits.block.BitStorageBlock.onUse(BitStorageBlock.java:90)
	at MC//net.minecraft.block.AbstractBlock$AbstractBlockState.onUse(AbstractBlock.java:964)
	at MC//net.minecraft.server.network.ServerPlayerInteractionManager.redirect$bnh000$carpet$activateWithOptionalCactus(ServerPlayerInteractionManager.java:2029)
	at MC//net.minecraft.server.network.ServerPlayerInteractionManager.interactBlock(ServerPlayerInteractionManager.java:338)
	at MC//net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerInteractBlock(ServerPlayNetworkHandler.java:1145)
	at MC//net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:34)
	at MC//net.minecraft.network.packet.c2s.play.PlayerInteractBlockC2SPacket.apply(PlayerInteractBlockC2SPacket.java:8)
	at MC//net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:22)
	at MC//net.minecraft.server.ServerTask.run(ServerTask.java:18)
	at MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:157)
	at MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:159)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:131)
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:752)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:140)
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.handler$bkj000$carpet$modifiedRunLoop(MinecraftServer.java:7394)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)`

**Comment by Zaromas** [comment]
This exact error is happening on my server too when trying to add water with a bucket

**Comment by ItsSunnyMonster** [comment]
Any updates on this issue? It is happening on my server too.

**Comment by squigglezworth** [comment]
I'm also encountering this error.

Minecraft 1.20.1
Fabric 0.16.9
Fabric API 0.92.2+1.20.1
Chisels&Bits 1.4.148
