### ISSUE TITLE
Server crashing randomly with c&b installed 

### ISSUE THREAD

**Issue by Kohtalee** [ChiselsAndBits/Chisels-and-Bits#1134]
I don’t exactly know what is causing this, but I have the crash log

(using aternos)

java.lang.Error: Watchdog
  | at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
  | at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.join(Unknown Source)
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity.method_11007(ChiseledBlockEntity.java:318)
  | at net.minecraft.class_2586.method_38244(class_2586.java:84)
  | at net.minecraft.class_2586.method_38242(class_2586.java:64)
  | at net.minecraft.class_2818.method_20598(class_2818.java:375)
  | at net.minecraft.class_2852.method_12410(class_2852.java:333)
  | at net.minecraft.class_3898.method_17228(class_3898.java:813)
  | at net.minecraft.class_3898.method_39925(class_3898.java:777)
  | at net.minecraft.class_3898.method_20605(class_3898.java:516)
  | at net.minecraft.class_3898.method_17233(class_3898.java:471)
  | at net.minecraft.class_3215.method_12127(class_3215.java:325)
  | at net.minecraft.class_3218.method_18765(class_3218.java:311)
  | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
  | at net.minecraft.class_3176.method_3813(class_3176.java:322)
  | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
  | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
  | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
  | at net.minecraft.server.MinecraftServer$Lambda$6236/0x000000080180fd38.run(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | A detailed walkthrough of the error, its code path and all known details is as follows:
  | ---------------------------------------------------------------------------------------
  |  
  | -- Head --
  | Thread: Server Watchdog
  | Stacktrace:
  | at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
  | at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.join(Unknown Source)
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity.method_11007(ChiseledBlockEntity.java:318)
  | at net.minecraft.class_2586.method_38244(class_2586.java:84)
  | at net.minecraft.class_2586.method_38242(class_2586.java:64)
  | at net.minecraft.class_2818.method_20598(class_2818.java:375)
  | at net.minecraft.class_2852.method_12410(class_2852.java:333)
  | at net.minecraft.class_3898.method_17228(class_3898.java:813)
  | at net.minecraft.class_3898.method_39925(class_3898.java:777)
  | at net.minecraft.class_3898.method_20605(class_3898.java:516)
  | at net.minecraft.class_3898.method_17233(class_3898.java:471)
  | at net.minecraft.class_3215.method_12127(class_3215.java:325)
  | at net.minecraft.class_3218.method_18765(class_3218.java:311)
  | at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
  | at net.minecraft.class_3176.method_3813(class_3176.java:322)
  | at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
  | at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
  | at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
  |  
  | -- Thread Dump --
  | Details:
  | Threads: "Reference Handler" daemon prio=10 Id=2 RUNNABLE
  | at java.base@17.0.4.1/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
  | at java.base@17.0.4.1/java.lang.ref.Reference.processPendingReferences(Unknown Source)
  | at java.base@17.0.4.1/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)
  |  
  |  
  | "Finalizer" daemon prio=8 Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@2fce31bc
  | at java.base@17.0.4.1/java.lang.Object.wait(Native Method)
  | -  waiting on java.lang.ref.ReferenceQueue$Lock@2fce31bc
  | at java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(Unknown Source)
  | at java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(Unknown Source)
  | at java.base@17.0.4.1/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
  |  
  |  
  | "Signal Dispatcher" daemon prio=9 Id=4 RUNNABLE
  |  
  |  
  | "Common-Cleaner" daemon prio=8 Id=10 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@2109da35
  | at java.base@17.0.4.1/java.lang.Object.wait(Native Method)
  | -  waiting on java.lang.ref.ReferenceQueue$Lock@2109da35
  | at java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(Unknown Source)
  | at java.base@17.0.4.1/jdk.internal.ref.CleanerImpl.run(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  | at java.base@17.0.4.1/jdk.internal.misc.InnocuousThread.run(Unknown Source)
  |  
  |  
  | "server-timer" daemon prio=5 Id=12 TIMED_WAITING on java.util.TaskQueue@25365acc
  | at java.base@17.0.4.1/java.lang.Object.wait(Native Method)
  | -  waiting on java.util.TaskQueue@25365acc
  | at java.base@17.0.4.1/java.util.TimerThread.mainLoop(Unknown Source)
  | at java.base@17.0.4.1/java.util.TimerThread.run(Unknown Source)
  |  
  |  
  | "JolokiaDiscoveryListenerThread-172.20.0.49" daemon prio=5 Id=13 RUNNABLE (in native)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.blockingReceive(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramSocketAdaptor.receive(Unknown Source)
  | at java.base@17.0.4.1/java.net.DatagramSocket.receive(Unknown Source)
  | at app//org.jolokia.discovery.MulticastSocketListenerThread.receiveMessage(MulticastSocketListenerThread.java:115)
  | ...
  |  
  | Number of locked synchronizers = 1
  | - java.util.concurrent.locks.ReentrantLock$NonfairSync@6034d00e
  |  
  |  
  | "HTTP-Dispatcher" daemon prio=5 Id=15 RUNNABLE (in native)
  | at java.base@17.0.4.1/sun.nio.ch.EPoll.wait(Native Method)
  | at java.base@17.0.4.1/sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
  | -  locked sun.nio.ch.Util$2@3ea94e65
  | -  locked sun.nio.ch.EPollSelectorImpl@511ef3f7
  | at java.base@17.0.4.1/sun.nio.ch.SelectorImpl.select(Unknown Source)
  | at platform/jdk.httpserver@17.0.4.1/sun.net.httpserver.ServerImpl$Dispatcher.run(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Jolokia Agent Cleanup Thread" daemon prio=5 Id=16 WAITING on java.lang.Thread@46693322
  | at java.base@17.0.4.1/java.lang.Object.wait(Native Method)
  | -  waiting on java.lang.Thread@46693322
  | at java.base@17.0.4.1/java.lang.Thread.join(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.join(Unknown Source)
  | at app//org.jolokia.jvmagent.CleanupThread.joinThreads(CleanupThread.java:110)
  | at app//org.jolokia.jvmagent.CleanupThread.run(CleanupThread.java:60)
  |  
  |  
  | "Notification Thread" daemon prio=9 Id=20 RUNNABLE
  |  
  |  
  | "jolokia-0" daemon prio=5 Id=25 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b2f41
  | at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
  | -  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1b2f41
  | at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.LinkedBlockingQueue.take(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
  | ...
  |  
  |  
  | "Timer hack thread" daemon prio=5 Id=32 TIMED_WAITING
  | at java.base@17.0.4.1/java.lang.Thread.sleep(Native Method)
  | at net.minecraft.class_156$8.run(class_156.java:784)
  |  
  |  
  | "Server thread" prio=5 Id=34 WAITING on java.util.concurrent.CompletableFuture$Signaller@5292477b
  | at java.base@17.0.4.1/jdk.internal.misc.Unsafe.park(Native Method)
  | -  waiting on java.util.concurrent.CompletableFuture$Signaller@5292477b
  | at java.base@17.0.4.1/java.util.concurrent.locks.LockSupport.park(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture$Signaller.block(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.waitingGet(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture.join(Unknown Source)
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity.method_11007(ChiseledBlockEntity.java:318)
  | -  locked java.lang.Object@74358341
  | ...
  |  
  |  
  | "DestroyJavaVM" prio=5 Id=36 RUNNABLE
  |  
  |  
  | "Server console handler" daemon prio=5 Id=37 RUNNABLE (in native)
  | at java.base@17.0.4.1/java.io.FileInputStream.readBytes(Native Method)
  | at java.base@17.0.4.1/java.io.FileInputStream.read(Unknown Source)
  | at java.base@17.0.4.1/java.io.BufferedInputStream.read1(Unknown Source)
  | at java.base@17.0.4.1/java.io.BufferedInputStream.read(Unknown Source)
  | -  locked java.io.BufferedInputStream@5d6d9e28
  | at java.base@17.0.4.1/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.cs.StreamDecoder.read(Unknown Source)
  | -  locked java.io.InputStreamReader@455d3e3
  | at java.base@17.0.4.1/java.io.InputStreamReader.read(Unknown Source)
  | ...
  |  
  |  
  | "Netty Epoll Server IO #0" daemon prio=5 Id=38 RUNNABLE (in native)
  | at io.netty.channel.epoll.Native.epollWait(Native Method)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:192)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:185)
  | at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290)
  | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Chisels and Bits Block save handler #1" daemon prio=5 Id=43 BLOCKED on java.lang.Object@74358341 owned by "Server thread" Id=34
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity.setOffThreadSaveResult(ChiseledBlockEntity.java:375)
  | -  blocked on java.lang.Object@74358341
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity.lambda$setChanged$6(ChiseledBlockEntity.java:353)
  | at mod.chiselsandbits.block.entities.ChiseledBlockEntity$Lambda$6703/0x00000008019204c0.run(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  | at java.base@17.0.4.1/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  | Number of locked synchronizers = 1
  | - java.util.concurrent.ThreadPoolExecutor$Worker@382a21f
  |  
  |  
  | "Query Listener #1" prio=5 Id=53 RUNNABLE
  | at java.base@17.0.4.1/sun.nio.ch.Net.poll(Native Method)
  | at java.base@17.0.4.1/sun.nio.ch.SelChImpl.park(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramChannelImpl.blockingReceive(Unknown Source)
  | at java.base@17.0.4.1/sun.nio.ch.DatagramSocketAdaptor.receive(Unknown Source)
  | at java.base@17.0.4.1/java.net.DatagramSocket.receive(Unknown Source)
  | at net.minecraft.class_3364.run(class_3364.java:258)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  | Number of locked synchronizers = 1
  | - java.util.concurrent.locks.ReentrantLock$NonfairSync@5ca277a3
  |  
  |  
  | "Server Watchdog" daemon prio=5 Id=54 RUNNABLE
  | at java.management@17.0.4.1/sun.management.ThreadImpl.dumpThreads0(Native Method)
  | at java.management@17.0.4.1/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
  | at java.management@17.0.4.1/sun.management.ThreadImpl.dumpAllThreads(Unknown Source)
  | at net.minecraft.class_3178.run(class_3178.java:49)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Java2D Disposer" daemon prio=10 Id=55 WAITING on java.lang.ref.ReferenceQueue$Lock@1ccb5ad3
  | at java.base@17.0.4.1/java.lang.Object.wait(Native Method)
  | -  waiting on java.lang.ref.ReferenceQueue$Lock@1ccb5ad3
  | at java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(Unknown Source)
  | at java.base@17.0.4.1/java.lang.ref.ReferenceQueue.remove(Unknown Source)
  | at java.desktop@17.0.4.1/sun.java2d.Disposer.run(Unknown Source)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Netty Epoll Server IO #1" daemon prio=5 Id=57 RUNNABLE (in native)
  | at io.netty.channel.epoll.Native.epollWait0(Native Method)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:176)
  | at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281)
  | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Netty Epoll Server IO #2" daemon prio=5 Id=58 RUNNABLE (in native)
  | at io.netty.channel.epoll.Native.epollWait0(Native Method)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:176)
  | at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:281)
  | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  | "Netty Epoll Server IO #3" daemon prio=5 Id=149 RUNNABLE (in native)
  | at io.netty.channel.epoll.Native.epollWait(Native Method)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:192)
  | at io.netty.channel.epoll.Native.epollWait(Native.java:185)
  | at io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290)
  | at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347)
  | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  | at java.base@17.0.4.1/java.lang.Thread.run(Unknown Source)
  |  
  |  
  |  
  | Stacktrace:
  | at net.minecraft.class_3178.run(class_3178.java:65)
  | at java.base/java.lang.Thread.run(Unknown Source)
 

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by marchermans** [comment]
What game version are you on? Are you running forge or fabric? What c and b version are you on?

**Comment by Shybella** [comment]
Same problem here, 1.18.2 Forge (Stoneblock3) 

Crash: https://pastebin.com/raw/dzEQC4fc
