### ISSUE TITLE
[1.19.2] [Critical] Create mod compatibility is broken (client crash)

### ISSUE THREAD

**Issue by vgrynch** [ChiselsAndBits/Chisels-and-Bits#1151]
MC 1.19.2
Forge 43.2.21
Create mod 1.19.2-0.5.1.c
Any time the chiseled block is used as part of the contraption, the client crashes with the exception below. No way to workaround but kill the contraption. 

```
[26Sept2023 10:49:51.469] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void com.jozufozu.flywheel.core.model.BlockModel.<init>(net.minecraft.client.resources.model.BakedModel, net.minecraft.world.level.block.state.BlockState)'
	at mod.chiselsandbits.forge.compat.create.ChiseledBlockInstance.lambda$init$4(ChiseledBlockInstance.java:68) ~[chisels-and-bits-forge-1.3.142.jar%23560!/:1.3.142]
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.lambda$model$0(InstancedMaterial.java:40) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23908!/:0.6.9-18]
	at java.util.HashMap.computeIfAbsent(HashMap.java:1220) ~[?:?]
	at com.jozufozu.flywheel.backend.instancing.instancing.InstancedMaterial.model(InstancedMaterial.java:39) ~[flywheel-forge-1.19.2-0.6.9-18.jar%23908!/:0.6.9-18]
	at mod.chiselsandbits.forge.compat.create.ChiseledBlockInstance.lambda$init$6(ChiseledBlockInstance.java:68) ~[chisels-and-bits-forge-1.3.142.jar%23560!/:1.3.142]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at mod.chiselsandbits.forge.compat.create.ChiseledBlockInstance.init(ChiseledBlockInstance.java:60) ~[chisels-and-bits-forge-1.3.142.jar%23560!/:1.3.142]
	at mod.chiselsandbits.forge.compat.create.ChiseledBlockInstance.lambda$new$0(ChiseledBlockInstance.java:42) ~[chisels-and-bits-forge-1.3.142.jar%23560!/:1.3.142]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23853!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.21.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
```

**Comment by marchermans** [comment]
Update to 1.20.x to get the update that fixes this.
Create sadly has no proper API and they broke their compatibility way after I closed support for 19.2.
So I am sorry but I am not able to fix this.
