### ISSUE TITLE
Crash - ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Utildayael** [ChiselsAndBits/Chisels-and-Bits#130]
This is an odd one. I was hold my chisel in my hand and looked at some EnderIO conduits / IC2 machines [I'm not entirely sure which I was looking at when it crashed] and boom, desktop.

Short error:

```
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -5
    at mod.chiselsandbits.chiseledblock.data.VoxelBlob.getBit(VoxelBlob.java:387)
    at mod.chiselsandbits.chiseledblock.data.VoxelBlob.get(VoxelBlob.java:402)
    at mod.chiselsandbits.chiseledblock.iterators.BaseChiselIterator.getVoxelBox(BaseChiselIterator.java:20)
    at mod.chiselsandbits.chiseledblock.iterators.BaseChiselIterator.getBoundingBox(BaseChiselIterator.java:60)
    at mod.chiselsandbits.core.ClientSide.drawHighlight(ClientSide.java:942)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_735_ClientSide_drawHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full log on Pastebin
http://pastebin.com/BfWr2Jz5

MC 1.10.2
Forge 12.18.1.2065
Chisel & Bits  11.10

Cheers

**Comment by AlgorithmX2** [comment]
Any idea how to reproduce this? I've seen this trace before, but didn't have any way to reproduce it, or really know how it happened.

**Comment by Utildayael** [comment]
When I logged on it seems I was holding a bit and pointing at an EnderIO conduit (the connector where you right click to set settings). 

Tried to reproduce and can't seem to get to fire again. :(

**Comment by ghost** [comment]
Same crashes, managing to reproduce it with pretty good success now.
http://pastebin.com/UJcj3fbY
http://pastebin.com/e5nrA2W0
http://pastebin.com/h0R3KAPa
Seems to happen when you aim at EnderIO conduit connector in certain bit placing mode(s).
Doesn't really seem to matter which conduit you are using or what they are connected to. I tested with both 'Fluid Conduit' and 'Ender Fluid Conduit's, but im assuming crash happens with any conduit.
Single bit, Line and Plane modes appeared to work just fine, but Connected Plane seems to be sure-fire crash. Here's a quick video of it https://youtu.be/r1EWvb7ZpaY

**Comment by AlgorithmX2** [comment]
Thanks for tracking down a way to reproduce that, I believe I've tracked down the cause and resolve it.
