### ISSUE TITLE
There was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by Vrandyke** [ChiselsAndBits/Chisels-and-Bits#15]
---- Minecraft Crash Report ----
// Everything's going to plan. No, really, that was supposed to happen.

Time: 3/13/16 8:48 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: mod.chiselsandbits.ChiselsAndBits
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:163)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:538)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:214)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:412)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
    at net.minecraft.client.main.Main.main(SourceFile:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mod.chiselsandbits.ChiselsAndBits
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:60)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:461)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:507)
    ... 10 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 38 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.8
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 133804384 bytes (127 MB) / 255066112 bytes (243 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.4.1563 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.8-11.14.4.1563.jar) 
    UC  Forge{11.14.4.1563} [Minecraft Forge](forge-1.8-11.14.4.1563.jar) 
    UE  chiselsandbits{1.6.2} [Chisels & Bits](mod) 
    Loaded coremods (and transformers): 
    GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3574' Renderer: 'Intel(R) HD Graphics 4600'

Suggestions?

**Comment by AlgorithmX2** [comment]
Something is off about how C&B is installed,

it should look something like this: chiselsandbits{1.6.2} [Chisels & Bits] (chiselsandbits-1.6.2.jar)

yours simply says "mod" where the jar name should be, make sure you have placed the jar in the mods folder, and not done anything odd like put it inside the MC jar.. or installed it as a core mod with a launcher.

**Comment by Vrandyke** [comment]
Alright I'll double check. Thanks for the tip

**Comment by Vrandyke** [comment]
How do I not install it as a core mod with a launcher? All it lets me do is choose which version I want and it downloads

**Comment by Vrandyke** [comment]
I'm also using WinRar and the Minecraft Forge Mod Loader. Neither of those would be causing an issue right? I do have the Forge set to the same version of Minecraft that the mod is. I've tried all I can think of to get this working and have even re-downloaded it a couple more times but am too afraid to download it to many more times in fear of putting my computer at risk. And further advice would be greatly appreciated

**Comment by AlgorithmX2** [comment]
What are you using winrar for?

I've attempted to break down installing a mod below, try this,
1. You just install Forge from http://files.minecraftforge.net/
2. Open the vanilla MC launcher.
3. Hit Edit Profile.
4. Next to "User Version" pick "release _-forge_" that you installed.
5. Hit "Open Game Dir" ( this opens a second window, for the next step ) and choose, "Save profile"
6. Add, or open the "mods" folder in the folder that the launcher opened for you in the previous step.
7. Download the mod jar, from http://minecraft.curseforge.com/projects/chisels-bits/files
8. Copy/Move the C&B jar from your downloads into this "mods" folder.
9. Hit Play on the vanilla launcher.

For reference by default on windows the path for mods using this method is:
C:\Users\MY USERNAME\AppData\Roaming\.minecraft\mods\

**Comment by Vrandyke** [comment]
Still nothing. It wouldn't be Winrar would it? I use it to download files of mods and make it easier to move them from point A to point B I can try to uninstall and see what that does

**Comment by AlgorithmX2** [comment]
Why would you need winrar to move files around? Are you extracting the jar file? If so don't do that.

**Comment by Vrandyke** [comment]
Alright then that must be the problem. I'll try it again and see what happens. Thanks for all your help

**Comment by Vrandyke** [comment]
Alright so my problem was like you mentioned. I was opening the file that was downloaded and extracting all the files to the mods folder for Minecraft rather than simply taking the whole Mod file that was in the downloads list and moving it there.

Thanks again for helping me get around this! xD

**Comment by AlgorithmX2** [comment]
No problem, Glad you figured it out.
