### ISSUE TITLE
Client crash when undoing, NPE chiselsandbits.client.gui.ChiselsAndBitsMenu

### ISSUE THREAD

**Issue by ProsperCraft** [ChiselsAndBits/Chisels-and-Bits#165]
Player reports this crash when "undoing chisel and bits stuff"
Trying to get more information from him.

http://pastebin.com/Ui1h5ijv

java.lang.NullPointerException: Unexpected error
    at mod.chiselsandbits.client.gui.ChiselsAndBitsMenu.func_73863_a(ChiselsAndBitsMenu.java:213)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
    at mod.chiselsandbits.core.ClientSide.onRenderGUI(ClientSide.java:490)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_719_ClientSide_onRenderGUI_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:205)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by AlgorithmX2** [comment]
The tool must somehow have stopped being... a tool and it got confused, should be fixed in a future build.
