### ISSUE TITLE
[1.11] Serverside log error spam

### ISSUE THREAD

**Issue by RViper80** [ChiselsAndBits/Chisels-and-Bits#207]
I keep getting this error repeatedly posted into the server logs whenever interacting (breaking/placing/chiseling) with a chisel & bits block.   It doesn't seem to have any negative effects other than inflating the log file size.

C&B 13.5, Forge 2188

```
22.12 20:25:21 [Server] Server thread/ERROR [chiselsandbits]: Unable to find TileEntity while interacting with block.
22.12 20:25:21 [Server] INFO mod.chiselsandbits.helpers.ExceptionNoTileEntity
22.12 20:25:21 [Server] INFO at mod.chiselsandbits.chiseledblock.BlockChiseled.<clinit>(BlockChiseled.java:279) ~[BlockChiseled.class:?]
22.12 20:25:21 [Server] INFO at mod.chiselsandbits.registry.ModBlocks.<init>(ModBlocks.java:86) ~[ModBlocks.class:?]
22.12 20:25:21 [Server] INFO at mod.chiselsandbits.core.ChiselsAndBits.preinit(ChiselsAndBits.java:119) ~[ChiselsAndBits.class:?]
22.12 20:25:21 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) ~[forge-1.11-13.19.1.2188-universal.jar:?]
22.12 20:25:21 [Server] INFO at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
22.12 20:25:21 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) ~[LoadController.class:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) ~[LoadController.class:?]
22.12 20:25:21 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.11.jar:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) ~[LoadController.class:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:615) ~[Loader.class:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
22.12 20:25:21 [Server] INFO at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:329) ~[FMLCommonHandler.class:?]
22.12 20:25:21 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[lh.class:?]
22.12 20:25:21 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]
22.12 20:25:21 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
```

**Comment by AlgorithmX2** [comment]
Have you enabled logTileErrors? for some reason?

If so turn that off, its default is off for a reason.

**Comment by RViper80** [comment]
I did not change that, but it indeed is true for some reason.   Might want to double check that it still is defaulted to false, since I haven't even looked in the configs since they generated new.  Will change it to false then.  Thanks :)

Edit:  Actually those might have been generated with that custom build you posted here for the tank fix, maybe you had them enabled then.

**Comment by AlgorithmX2** [comment]
I don't believe that I've ever set it to true, and as it stands now the default is certainly false. I don't know how that could have changed unless you were changing the settings for some reason, maybe trying to fix something? test something?

I don't know. Its also probably not really worth worrying about either.
