### ISSUE TITLE
Crash when keybind conflicts

### ISSUE THREAD

**Issue by tyler489** [ChiselsAndBits/Chisels-and-Bits#269]
For any bug reports please provide the following,

* MC Version: 1.10
* C&B Version: Let me check
* Do You have Optifine: no

Set my chisel menu key to left control and the client refuses to load with that crash report
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.7.241-universal.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  IvToolkit (IvToolkit-1.3.2.1-1.10.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.65-beta.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.3.207-universal.jar)
  PlusTiC (plustic-4.3.0.2.jar)
  MalisisCorePlugin (malisiscore-1.10.2-4.4.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ForgelinPlugin (Forgelin-1.4.1.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.9.15.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 5/17/17 3:53 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mod.chiselsandbits.client.ModConflictContext.isActive(ModConflictContext.java:128)
	at mod.chiselsandbits.client.ModConflictContext$2.isActive(ModConflictContext.java:47)
	at net.minecraft.client.settings.KeyBinding.isActiveAndMatches(KeyBinding.java:201)
	at net.minecraftforge.client.settings.KeyBindingMap.getBinding(KeyBindingMap.java:62)
	at net.minecraftforge.client.settings.KeyBindingMap.lookupActive(KeyBindingMap.java:46)
	at com.rwtema.extrautils2.keyhandler.KeyHandler.getIsKeyPressed(KeyHandler.java:26)
	at com.rwtema.extrautils2.keyhandler.KeyAlt.onPress(KeyAlt.java:29)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_KeyAlt_onPress_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:339)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1650)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by tyler489** [comment]
i believe im using V12.12 playing the foolcraft modpack

**Comment by AlgorithmX2** [comment]
Looks like this issue was already fixed in 1.11 but not in 1.10, XU is testing hotkeys from the menu for some reason which means that the player doesn't exist.

**Comment by tyler489** [comment]
alright ill go report it to extrautlities to.

**Comment by AlgorithmX2** [comment]
https://www.dropbox.com/s/gtqsx2s57jrg5g8/chiselsandbits-12.0.jar?dl=1 should resolve this issue, can you please confirm?

**Comment by tyler489** [comment]
Unfortunitly im playing on a server and i cant update my mods but i will ask the pack dev to update

**Comment by AlgorithmX2** [comment]
You don't need to keep this version installed, I'm just curious if this build fixes your issue,  from the looks of it it crashed on the main menu, so that should be testable without connecting to the server?
