### ISSUE TITLE
Minecraft launching options with jei

### ISSUE THREAD

**Issue by MartinMeij** [ChiselsAndBits/Chisels-and-Bits#378]
hi im using the minecraft vesion 1.11.2 and im playing with mods but when in start minecraft and forge is almost done with loading the launger appears and it gives me this 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.328-universal.jar)
  CorePlugin (FluxedRedstone-2.6.1.59.jar)
  RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 3/30/18 10:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Just Enough Items (jei)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/util/StatCollector
	at mezz.jei.util.Translator.translateToLocal(Translator.java:13)
	at mezz.jei.config.LocalizedConfiguration.<init>(LocalizedConfiguration.java:22)
	at mezz.jei.config.Config.preInit(Config.java:82)
	at mezz.jei.ProxyCommonClient.preInit(ProxyCommonClient.java:50)
	at mezz.jei.JustEnoughItems.preInit(JustEnoughItems.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.util.StatCollector
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 177498104 bytes (169 MB) / 419430400 bytes (400 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2579 Optifine OptiFine_1.11.2_HD_U_C7 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2579.jar) 
	UCH	forge{13.20.1.2579} [Minecraft Forge] (forge-1.11.2-13.20.1.2579.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	codechickenlib{3.0.0.328} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.328-universal.jar) 
	UCH	brandonscore{2.2.5} [Brandon's Core] (BrandonsCore-1.11.2-2.2.5.135-universal.jar) 
	UCH	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
	UCH	draconicevolution{2.2.5} [Draconic Evolution] (Draconic-Evolution-1.11.2-2.2.5.271-universal.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.7.4.jar) 
	UCH	zerocore{1.11.2-0.1.1.0} [Zero CORE] (zerocore-1.11.2-0.1.1.0.jar) 
	UCH	bigreactors{1.11.2-0.4.5.46} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.46.jar) 
	UCH	reborncore{2.16.1.115} [Reborn Core] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCH	reborncore-mcmultipart{2.16.1.115} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCH	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.1.59.jar) 
	UCH	waila{1.8.15} [Waila] (Hwyla-Mod-1.11.2.jar) 
	UCH	ironchest{1.11.2-7.0.25.815} [Iron Chest] (ironchest-1.11.2-7.0.25.815.jar) 
	UCE	jei{4.5.0.295} [Just Enough Items] (jei_1.11.2-4.5.0.295.jar) 
	UCH	journeymap{1.11.2-5.5.2} [JourneyMap] (journeymap-1.11.2-5.5.2.jar) 
	UCH	mcmultipart{2.0.2} [MCMultiPart] (MCMultiPart-2.0.2.jar) 
	UCH	morefurnaces{1.9.5} [More Furnaces] (More-Furnaces-Mod-1.11.2.jar) 
	UCH	xreliquary{1.11.2-1.3.4.678} [Reliquary] (Reliquary-Mod-1.11.2.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
  cubex2.cxlibrary.CoreModTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.328-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
CorePlugin (FluxedRedstone-2.6.1.59.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.163.2560' Renderer: 'AMD Radeon(TM) R5 Graphics'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.16.1.115
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 1
	OptiFine Version: OptiFine_1.11.2_HD_U_C7
	Render Distance Chunks: 3
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.163.2560
	OpenGlRenderer: AMD Radeon(TM) R5 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

can somebody help me

**Comment by AlgorithmX2** [comment]
I'm a it confused why you've sent this to me? @Mezz is this something on your end?

**Comment by MartinMeij** [comment]
Oh sorry ive put it into the wrong place forgive me
