### ISSUE TITLE
Mod ignored on server start

### ISSUE THREAD

**Issue by vellak** [ChiselsAndBits/Chisels-and-Bits#414]
HI,
Ive been getting a strange issue where the mod gets ignored for the server, but client side it works fine.
All mods are updated to their latest version.

Error log on server start:

`[10:55:58] [Server thread/WARN] [FML]: Zip file chiselsandbits-14.20.jar failed to read properly, it will be ignored
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_171]
	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_171]
	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_171]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_171]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:56) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]

//Not sure if this is part of the error, but was directly underneath it so I included it

[10:55:58] [Server thread/ERROR] [FML]: Unable to construct net.minecraftforge.fml.common.Mod container
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedConstructorAccessor64.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_171]
	at net.minecraftforge.fml.common.ModContainerFactory.build(ModContainerFactory.java:73) [ModContainerFactory.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.findClassesASM(JarDiscoverer.java:114) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:77) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:425) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:566) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: The modId CodeChickenCore must be all lowercase.
	at net.minecraftforge.fml.common.FMLModContainer.sanityCheckModId(FMLModContainer.java:145) ~[FMLModContainer.class:?]
	at net.minecraftforge.fml.common.FMLModContainer.<init>(FMLModContainer.java:129) ~[FMLModContainer.class:?]
	... 16 more`

For any bug reports please provide the following details as well,
* MC Version: 1.12.2
* C&B Version: 14.20
* Do You have Optifine: yes

**Comment by vellak** [comment]
Ok I feel stupid now, I noticed the filesize of the mods where different between client and server??? Uploaded the clients's one server side and it seems to be fixed....
