### ISSUE TITLE
Random crash with MCMP integration

### ISSUE THREAD

**Issue by asiekierka** [ChiselsAndBits/Chisels-and-Bits#418]
```
[07:02:38] [main/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.10.0-1.12.2.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  LoadingPlugin (Quark-r1.4-125.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 8/13/18 7:02 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.setBlob(TileEntityBlockChiseled.java:648)
	at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.setBlob(TileEntityBlockChiseled.java:551)
	at mod.chiselsandbits.integration.mcmultipart.ChiseledBlockPart.isBlobOccluded(ChiseledBlockPart.java:41)
	at mod.chiselsandbits.chiseledblock.TileEntityBlockChiseled.canMerge(TileEntityBlockChiseled.java:885)
	at mod.chiselsandbits.core.ClientSide.doGhostForChiseledBlock(ClientSide.java:1264)
	at mod.chiselsandbits.core.ClientSide.drawLast(ClientSide.java:1232)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_598_ClientSide_drawLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:181)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1432)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1118)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Comment by AlgorithmX2** [comment]
That's an odd one, I think the player must be hold a block or design that is now empty. This should fix it however.
