### ISSUE TITLE
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail The game crashed whilst there was a severe problem during mod loading that has caused the game to fail Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)

### ISSUE THREAD

**Issue by DragonaxeYT** [ChiselsAndBits/Chisels-and-Bits#461]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 4/16/19 6:19 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:61)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:67)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 554833880 bytes (529 MB) / 1207959552 bytes (1152 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_D3 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID              | Version                  | Source                                  | Signature                                |
	|:------- |:--------------- |:------------------------ |:--------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft       | 1.12.2                   | minecraft.jar                           | None                                     |
	| UCHIJA  | mcp             | 9.42                     | minecraft.jar                           | None                                     |
	| UCHIJA  | FML             | 8.0.99.99                | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge           | 14.23.5.2768             | forge-1.12.2-14.23.5.2768.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | codechickenlib  | 3.2.2.353                | CodeChickenLib-1.12.2.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | chickenchunks   | 2.4.1.73                 | ChickenChunks-Mod-1.12.2.jar            | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | waila           | 1.8.26                   | Hwyla-Mod-1.12.2.jar                    | None                                     |
	| UCHIJA  | inventorytweaks | 1.63+release.109.220f184 | Inventory-Tweaks-Mod-1.12.2.jar         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJA  | jei             | 4.9.1.168                | jei_1.12.2-4.9.1.168.jar                | None                                     |
	| UCHIJA  | journeymap      | 1.12.2-5.5.2             | JourneyMap-Mod-1.12.2-Unlimited.jar     | None                                     |
	| UCHIJA  | malisiscore     | 1.12.2-6.4.0             | MalisisCore-1.12.2.jar                  | None                                     |
	| UCHIJA  | malisisdoors    | 1.12.2-7.3.0             | MalisisDoors-Mod-1.12.2.jar             | None                                     |
	| UCHIJEE | nei             | 2.4.1                    | Not-Enough-Items-1.12.2-Recommended.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ   | oreexcavation   | 1.4.105                  | Ore-Excavation-Mod-1.12.1.jar           | None                                     |
	| UCHIJ   | pixelmon        | 7.0.5                    | Pixelmon-1.12.2-7.0.5-universal.jar     | None                                     |
	| UCHIJ   | wawla           | 2.5.257                  | Wawla-1.12.2-2.5.257.jar                | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (Inventory-Tweaks-Mod-1.12.2.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4836' Renderer: 'Intel(R) HD Graphics 620'
	OptiFine Version: OptiFine_1.12.2_HD_U_D3
	OptiFine Build: 20180515-125031
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 - Build 22.20.16.4836
	OpenGlRenderer: Intel(R) HD Graphics 620
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by DragonaxeYT** [comment]
I need to know how to solve this. Pls help.

Btw, I do not know if I did this correctly.

**Comment by AlgorithmX2** [comment]
I'm not sure your asking me, your not even using my mod. Your issue seems related to "Not Enough Items" as it indicates in the title.
