### ISSUE TITLE
C&B+TofuCraftReload >0.5.4Version was crash

### ISSUE THREAD

**Issue by Huaxidesu** [ChiselsAndBits/Chisels-and-Bits#475]
Time: 2019-07-22 18:04:29 CST
Description: Initializing game

java.lang.NullPointerException
at cn.mcmod.tofucraft.block.BlockTofu.damageDropped(BlockTofu.java:102)
at mod.chiselsandbits.items.ItemChiseledBit.getBitStateName(ItemChiseledBit.java:155)
at mod.chiselsandbits.items.ItemChiseledBit.getBitTypeName(ItemChiseledBit.java:207)
at mod.chiselsandbits.items.ItemChiseledBit.getItemStackDisplayName(ItemChiseledBit.java:214)
at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:617)
at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:662)
at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
at net.minecraft.client.Minecraft$$Lambda$2150.000000002F4067D0.apply(Unknown Source)
at net.minecraft.client.util.SearchTree.index(SourceFile:49)
at net.minecraft.client.util.SearchTree.add(SourceFile:44)
at net.minecraft.client.Minecraft$$Lambda$2191.000000002F40B190.accept(Unknown Source)
at java.lang.Iterable.forEach(Iterable.java:75)
at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:590)
at net.minecraft.client.Minecraft.init(Minecraft.java:529)
at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

> https://github.com/0999312/TofuCraftReload/issues/38
![TIM截图20190722191621](https://user-images.githubusercontent.com/45794248/61628632-6c725100-acb5-11e9-8d53-8cb1749545d0.png)

> 

* MC Version:1.12.2
* C&B Version:14.32

**Comment by Panduso** [comment]
he's not working on the mod anymore, there's no point in doing this

**Comment by Aeltumn** [comment]
This is a bug but it won't be fixed as C&B for 1.12 isn't receiving updates anymore.
