### ISSUE TITLE
Crash when joining server.

### ISSUE THREAD

**Issue by Darkhax** [ChiselsAndBits/Chisels-and-Bits#48]
I encountered [this](https://www.dropbox.com/s/dnggsfb1i4yh727/fml-client-latest.log?dl=0) crash when joining a server. The stack trace seems to point to Chisel and Bits. The log is extremely long, with the stack trace happening on line 8453. I have separated out the actual crash which you can find [here](https://gist.github.com/darkhax/c943abce208fc0245c0df4773b653ba6). 

Version used is 9.16

**Comment by AlgorithmX2** [comment]
The Exceptions you inciated were not acctually your crash, but C&B's threads being shutdown un-unexpectedly by interruption ( the real crash )

Your real crash is.

```
java.lang.NullPointerException: Unexpected error
    at net.minecraft.world.World.func_72939_s(World.java:1782)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1783)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Which is a crash in updateEntities unfortunately that doesn't indicate any mod in particular.

**Comment by Darkhax** [comment]
Just noticed that, looks like a dead end. Fortunately the crash can't be reproduced reliably.
