### ISSUE TITLE
Issue Upon Startup

### ISSUE THREAD

**Issue by DreamingGalaxys** [ChiselsAndBits/Chisels-and-Bits#490]
I am trying to run 1.11.2 Chisel and bits 13.16 and it says something about the field size: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LittlePatchingLoader (LittleTiles_v1.5.0-pre122_mc1.11.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.11.2.jar)
  LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 1/12/20 7:16 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Chisels & Bits (chiselsandbits)
Caused by: io.netty.handler.codec.EncoderException: java.io.EOFException: fieldSize is too long! Length is 28276, but maximum is 213
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:316)
	at mod.chiselsandbits.client.ClipboardStorage.read(ClipboardStorage.java:95)
	at mod.chiselsandbits.client.CreativeClipboardTab.load(CreativeClipboardTab.java:31)
	at mod.chiselsandbits.core.ChiselsAndBits.preinit(ChiselsAndBits.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:647)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:276)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.io.EOFException: fieldSize is too long! Length is 28276, but maximum is 213
	at io.netty.buffer.ByteBufInputStream.checkAvailable(ByteBufInputStream.java:253)
	at io.netty.buffer.ByteBufInputStream.readFully(ByteBufInputStream.java:174)
	at java.io.DataInputStream.readUTF(DataInputStream.java:609)
	at io.netty.buffer.ByteBufInputStream.readUTF(ByteBufInputStream.java:228)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:126)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:87)
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:312)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 427235416 bytes (407 MB) / 872415232 bytes (832 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2588 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2588.jar) 
	UCH	forge{13.20.1.2588} [Minecraft Forge] (forge-1.11.2-13.20.1.2588.jar) 
	UCH	creativecoredummy{1.0.0} [CreativeCoreDummy] (minecraft.jar) 
	UCH	littletilescore{1.0.0} [LittleTilesCore] (minecraft.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCE	chiselsandbits{13.16} [Chisels & Bits] (chiselsandbits-13.16.jar) 
	UCH	creativecore{1.9.9} [CreativeCore] (CreativeCore_v1.9.35_mc1.11.2.jar) 
	UCH	littletiles{1.5.0} [LittleTiles] (LittleTiles_v1.5.0-pre122_mc1.11.2.jar) 
	UCH	mcmultipart{2.0.2} [MCMultiPart] (MCMultiPart-2.0.2.jar) 
	Loaded coremods (and transformers): 
LittlePatchingLoader (LittleTiles_v1.5.0-pre122_mc1.11.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
CreativePatchingLoader (CreativeCore_v1.9.35_mc1.11.2.jar)
  com.creativemd.creativecore.core.CreativeCoreTransformer
LittleLatePatchingLoader (LittleTilesCore-v1.0.0.jar)
  com.creativemd.littletiles.LittleTilesLateTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 432.00' Renderer: 'GeForce GTX 1080/PCIe/SSE2'

For any bug reports please provide the following details as well,
* MC Version: 1.11.2
* C&B Version: 13.16
* Do You have Optifine: Nope

**Comment by Aeltumn** [comment]
This is unfortunately a known issue for 1.11, this was also reported in #487. I commented the following there:
> Could you try removing the chiselsandbits_clipboard.cfg file from the /config/ directory?
> Otherwise try setting the configuration option persistCreativeClipboard to false.
