### ISSUE TITLE
There was a severe problem during mod loading that has caused the game to fail????

### ISSUE THREAD

**Issue by DankSaNiK4Life** [ChiselsAndBits/Chisels-and-Bits#508]
* MC Version: 1.12.2
* C&B Version: 14.33
* Do You have Optifine: No

Hi I have recently decide to make a little funny pack for my friends and have decided to try this mod first. When I launch it on twitch Chisel and Bits cause a crash. However when I try the mod on MultiMC it works fine why is this??

Heres the Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/25/20 4:07 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: chiselsandbits Failed load class: mod.chiselsandbits.core.ChiselsAndBits
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mod.chiselsandbits.core.ChiselsAndBits
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	... 36 more
Caused by: java.io.FileNotFoundException: C:\Users\Aaron\Twitch\Minecraft\Instances\SaNiK's MelonCraft Pack (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:220)
	at java.util.zip.ZipFile.<init>(ZipFile.java:150)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getJarFile(JarURLConnection.java:89)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:145)
	... 42 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 269011768 bytes (256 MB) / 919076864 bytes (876 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                                        | Signature                                |
	|:----- |:-------------- |:------------ |:--------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft      | 1.12.2       | minecraft.jar                                 | None                                     |
	| LC    | mcp            | 9.42         | minecraft.jar                                 | None                                     |
	| LC    | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge          | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | chiseled_me    | 2.0.0.1      | chiseled-me-1.12.2-2.0.0.1.jar                | c677c954974252994736eb15e855e1e6fc5a2e62 |
	| LE    | chiselsandbits | 14.33        | chiselsandbits-14.33.jar                      | None                                     |
	| L     | codechickenlib | 3.2.3.358    | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | None                                     |

	Loaded coremods (and transformers): 
Chiseled Me ASM (chiseled-me-1.12.2-2.0.0.1.jar)
  dev.necauqua.mods.cm.asm.Plugin
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 451.48' Renderer: 'GeForce GTX 1660/PCIe/SSE2'

**Comment by Aeltumn** [comment]
Something went wrong during startup, it might be because your folder name "SaNiK's MelonCraft Pack" contains a ' and spaces, could be worth testing if it works if the folder name contains neither of those things. Although I'm not 100% sure if that'll fix it.

**Comment by DankSaNiK4Life** [comment]
Oh wow, it actually worked lol! Didn't expect that. Thanks sooo muchhhhhhhhhhh!!!!!!!
