### ISSUE TITLE
There was a severe problem during mod loading that has caused the game to fail.

### ISSUE THREAD

**Issue by pamaguin** [ChiselsAndBits/Chisels-and-Bits#512]
---- Minecraft Crash Report ----
// Don't do that.

Time: 9/23/20 6:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thehippomaster/MutantCreatures/MutantSkeleton
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: thehippomaster/MutantCreatures/MutantSkeleton
	at thehippomaster.MutantCreatures.item.ChemicalX.<clinit>(ChemicalX.java:83)
	at thehippomaster.MutantCreatures.MutantCreatures.preInit(MutantCreatures.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: thehippomaster.MutantCreatures.MutantSkeleton
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: thehippomaster/AnimationAPI/IAnimatedEntity
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: thehippomaster.AnimationAPI.IAnimatedEntity
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1551601408 bytes (1479 MB) / 2147483648 bytes (2048 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 34 mods loaded, 34 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCH	FamiliarsAPI{1.7.2} [Familiars API] (FamiliarsAPI-1.7.2.jar) 
	UCH	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
	UCH	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16 (1).jar) 
	UCH	DamageIndicatorsMod{3.3.2} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.3.2.jar) 
	UCH	animatedplayer{1.5.1} [Animated Player Mod] (AnimatedPlayer-1.7.10-1.5.1.jar) 
	UCH	gibby_dungeons{1.3} [Arcana RPG] (Arcana RPG 1.3 - 1.7.10.jar) 
	UCH	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCH	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCH	BackTools{4.0.0} [BackTools] (BackTools-4.0.0.jar) 
	UCH	CustomPets{1.0.5} [Custom Pets] (custompets-1.7.10-1.0.5-universal.jar) 
	UCH	dungeonpack{1.7.10-1.0} [Dungeon Pack] (Dungeon-Pack-Mod-1.7.10.jar) 
	UCH	DynamicLights{1.3.9a} [Dynamic Lights] (Dynamic+Lights-1.3.9a-MC1.7.10.jar) 
	UCH	mwaw{1.7.10-0.0.1} [Elemental Witch Mod] (Elemental-Witch-Mod-1.7.10.jar) 
	UCH	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCH	golems{1.20} [Extra Golems] (Extra-Golems[1.7.10]-1.20.jar) 
	UCH	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212-Core-1.7.10 (1).jar) 
	UCH	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCH	headcrumbs{1.7.4} [Headcrumbs] (Headcrumbs-1.7.4.jar) 
	UCH	InfernalMobs{1.6.0} [Infernal Mobs] (InfernalMobs-1.7.10.jar) 
	UCH	lootbags{2.0.17} [Loot Bags] (LootBags-1.7.10-2.0.17.jar) 
	UCH	lucky{5.1.0} [Lucky Block] (luckyblock-1.7.10-1.jar) 
	UCH	MobAmputation{4.0.1} [MobAmputation] (MobAmputation-4.0.1.jar) 
	UCH	MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar) 
	UCH	Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar) 
	UCE	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCH	nevermine{Tslat-1.1.2} [Advent of Ascension] (Nevermine-Tslat-1.1.2.jar) 
	UCH	pandorasbox{2.0.1} [Pandora's Box] (PandorasBox-2.1.jar) 
	UCH	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-Mod-by-grim3212-1.7.10.jar) 
	UCH	Treecapitator{1.7.2} [Treecapitator] (Tree-Capitator-Mod-1.7.2.jar) 
	UCH	youtubers{1.8.0} [Youtubers+ Mod] (youtubers-1.8.0-MC1.7.10.jar) 
	UCH	voxelmap{1.7.10} [VoxelMap No Radar] (Zans-Minimap-No-Radar-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1060/PCIe/SSE2'

**Comment by Aeltumn** [comment]
This is not an issue with Chisels & Bits, it's an issue with Mutant Creatures.
