### ISSUE TITLE
Texture dont loading with Optifine and/ game crashing after clicking on chisel and bits TAB

### ISSUE THREAD

**Issue by ThereWeAre** [ChiselsAndBits/Chisels-and-Bits#519]
Hello, my problem is that the textures didnt load when i have optifine in my mods foler.
Also i have a problem that every time when i clicked on the chisel and bits TAB in creative mode my game crashes.
I tested it with only the chisel and bits mod in the mod folder but the problem is still the same.

For any bug reports please provide the following details as well,
* MC Version: 1.16.1
* C&B Version: chiselsandbits-0.0.6-BETA.jar
* Do You have Optifine: yes

**Comment by ThereWeAre** [comment]
This is the Crash Log


---- Minecraft Crash Report ----
// Don't do that.

Time: 14.10.20 19:41
Description: Rendering item

java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_51] {}
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_51] {}
	at net.minecraft.util.NonNullList.get(SourceFile:46) ~[?:?] {re:classloading}
	at mod.chiselsandbits.render.bit.BitItemSmartModel.getCachedModel(BitItemSmartModel.java:45) ~[?:?] {re:classloading}
	at mod.chiselsandbits.render.bit.BitItemSmartModel.func_239290_a_(BitItemSmartModel.java:82) ~[?:?] {re:classloading}
	at mod.chiselsandbits.client.model.baked.BaseSmartModel$OverrideHelper.func_239290_a_(BaseSmartModel.java:43) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.ItemRenderer.func_184393_a(ItemRenderer.java:192) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:261) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:253) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:481) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:951) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:582) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.1-32.0.108.jar:32.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1638249646.call(Unknown Source) [forge-1.16.1-32.0.108.jar:32.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:46)
	at mod.chiselsandbits.render.bit.BitItemSmartModel.getCachedModel(BitItemSmartModel.java:45)
	at mod.chiselsandbits.render.bit.BitItemSmartModel.func_239290_a_(BitItemSmartModel.java:82)
	at mod.chiselsandbits.client.model.baked.BaseSmartModel$OverrideHelper.func_239290_a_(BaseSmartModel.java:43)
	at net.minecraft.client.renderer.ItemRenderer.func_184393_a(ItemRenderer.java:192)

-- Item being rendered --
Details:
	Item Type: block_bit
	Registry Name: chiselsandbits:block_bit
	Item Damage: 0
	Item NBT: {id:0}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_239387_b_(ItemRenderer.java:261)
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:253)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_238746_a_(ContainerScreen.java:237)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_230430_a_(ContainerScreen.java:106)
	at net.minecraft.client.gui.DisplayEffectsScreen.func_230430_a_(DisplayEffectsScreen.java:48)
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.func_230430_a_(CreativeScreen.java:608)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:327)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (243, 98). Absolute: (730.000000, 295.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['ThereWeAre'/218, l='ClientLevel', x=-133.50, y=75.00, z=-42.50]]
	Chunk stats: Client Chunk Cache: 1681, 447
	Level dimension: minecraft:overworld
	Level spawn location: World: (-128,73,-48), Chunk: (at 0,4,0 in -8,-3; contains blocks -128,0,-48 to -113,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 106 game time, 106 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:446)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:598)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$411/1638249646.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1188739152 bytes (1133 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		chiselsandbits-0.0.6-BETA.jar Chisels & bits {chiselsandbits@NONE DONE}
	Launched Version: 1.16.1-forge-32.0.108
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources
	Current Language: Deutsch (Deutschland)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor

**Comment by xVIPERx98** [comment]
Also having this issue with clicking on the tab. I have Just Enough Items installed, and I can't see any of the Chisel and Bits equipment in that listing.


[crash-2020-10-16_16.17.30-client.txt](https://github.com/AlgorithmX2/Chisels-and-Bits/files/5394163/crash-2020-10-16_16.17.30-client.txt)

**Comment by marchermans** [comment]
Fixed in the upcoming 1.0.11 or 1.1.5 releases
