### ISSUE TITLE
Breaking a chiselled block causes the game to crash

### ISSUE THREAD

**Issue by vinnyg0621** [ChiselsAndBits/Chisels-and-Bits#523]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/26/20 1:23 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51] {}
	at mod.chiselsandbits.client.model.baked.DataAwareChiseledBlockBakedModel.getModelData(DataAwareChiseledBlockBakedModel.java:112) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:82) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:894) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:721) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:180) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$8158/1780403245.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_51] {}
	at mod.chiselsandbits.client.model.baked.DataAwareChiseledBlockBakedModel.getModelData(DataAwareChiseledBlockBakedModel.java:112) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:82) ~[?:?] {re:classloading,xf:OptiFine:default}
-- Block being tesselated --
Details:
	Block: Block{chiselsandbits:chiseledwood}[full_block=false]
	Block location: World: (412,70,-276), Chunk: (at 12,4,12 in 25,-18; contains blocks 400,0,-288 to 415,255,-273), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) ~[?:?] {re:classloading,xf:OptiFine:default}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['vinnyg0621'/102, l='ClientLevel', x=412.07, y=69.94, z=-276.44]]
	Chunk stats: Client Chunk Cache: 289, 143
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,69,208), Chunk: (at 0,4,0 in -4,13; contains blocks -64,0,208 to -49,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 73621 game time, 7000 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1974) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$3(ChunkRenderDispatcher.java:186) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$8234/1138639933.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1523098544 bytes (1452 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.16.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.16.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.16.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.16.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.16.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.3-0.3.4.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.16
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.16-client.jar Minecraft {minecraft@1.16.3 DONE}
		ImmersiveEngineering-1.16.3-4.1.0-124.jar Immersive Engineering {immersiveengineering@1.16.3-4.1.0-124 DONE}
		BiomesOPlenty-1.16.3-12.0.0.409-universal.jar Biomes O' Plenty {biomesoplenty@1.16.3-12.0.0.409 DONE}
		mining-helmet-1.16.3-1.0.9.jar Mining Helmet {mining_helmet@1.0.9 DONE}
		pamhc2crops-1.16.3-1.0.1.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		platforms-1.16-1.7.6.jar Platforms {platforms@1.7.6 DONE}
		OptiForge-MC1.16.3-0.3.4.jar OptiForge {optiforge@0.3.4 DONE}
		simplefarming-1.16.3-1.3.3.jar Simple Farming {simplefarming@1.16.3-1.3.3 DONE}
		JustARaftMod-1.16.3-1.1.3.jar Just A Raft Mod {justaraftmod@1.1.3 DONE}
		pitg-1.16.3-1.4.1.jar Pane In The Glass {pitg@1.16.3-1.4.1 DONE}
		Mantle-1.16.3-1.6.40.jar Mantle {mantle@1.6.40 DONE}
		WallpaperCraft-1.16.3-1.4.5.jar Wallpapercraft {wallpapercraft@1.4.5 DONE}
		pamhc2foodcore-1.16.3-1.0.0.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		AutoRegLib-1.6-46.jar AutoRegLib {autoreglib@1.6-46 DONE}
		sit-1.16.2-v1.3.jar Sit {sit@v1.3 DONE}
		Survivalist-1.16.3-3.3.1.jar Survivalist {survivalist@3.3.1 DONE}
		mcw-doors-1.0.1fix-mc1.16.3-1.16.2.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		furniture-7.0.0-pre19-1.16.3.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre19 DONE}
		engineersdecor-1.16.3-1.1.2.jar Engineer's Decor {engineersdecor@1.1.2 DONE}
		sculktastic.jar Sculktastic {sculktastic@1.16.3-2.0 DONE}
		forge-1.16.3-34.1.16-universal.jar Forge {forge@34.1.16 DONE}
		Quark-r2.4-269.jar Quark {quark@r2.4-269 DONE}
		Ceramics-1.16.3-1.5.1.jar Ceramics {ceramics@1.5.1 DONE}
		shetiphiancore-1.16-3.8.4.jar ShetiPhian-Core {shetiphiancore@3.8.4 DONE}
		Bundles-1.3.jar Bundles! {bundles@1.3 DONE}
		playereatinganimation-1.1.jar Player Eating Animation {playereatinganimation@1.1 DONE}
		chiselsandbits-0.2.2-ALPHA.jar Chisels & bits {chiselsandbits@NONE DONE}
	Crash Report UUID: a221cb52-98fc-4d2a-ad29-bbdca91bd2e0
	Launched Version: 1.16.3-forge-34.1.16
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ IllegalStateException: Rendersystem called from wrong thread
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	GPU Warnings: renderer: Stencil enabled in Immersive Engineering config
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, quark:emote_resources (incompatible), file/fancier-fences-e1980.zip (incompatible), file/Round-Trees-3.0-§31.15+§o.zip (incompatible), file/Custom font 1.16
	Current Language: English (US)
	CPU: 4x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre2
	OptiFine Build: 20201007-190609
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13547 Compatibility Profile Context 25.20.15030.4
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by marchermans** [comment]
This seems to be an optifine related bug. Since I can not seem to reproduce it.

Also please use the template and provide more details.
