### ISSUE TITLE
Client crash with region drawn mode in Multyplayer

### ISSUE THREAD

**Issue by czarcipomiot** [ChiselsAndBits/Chisels-and-Bits#584]
Only client crash. Server just give message about leaving player. Single player with this same configuration works fine.
 
Client crash when using region drawn mode to destory more than half block (vanilla block) or fill to full block with any mode.

Tested on all graphis options from low to highest and still this same result.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 1/16/21 1:54 PM
Description: Tesselating block in world

java.lang.NullPointerException: Tesselating block in world
  at mod.chiselsandbits.render.chiseledblock.ChiseledBlockSmartModel.getCachedModel(ChiseledBlockSmartModel.java:79) ~[chiselsandbits:?] {re:classloading}
  at mod.chiselsandbits.client.model.baked.DataAwareChiseledBlockBakedModel.getModelData(DataAwareChiseledBlockBakedModel.java:89) ~[chiselsandbits:?] {re:classloading}
  at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:63) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:847) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
  at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
  at mod.chiselsandbits.render.chiseledblock.ChiseledBlockSmartModel.getCachedModel(ChiseledBlockSmartModel.java:79) ~[chiselsandbits:?] {re:classloading}
  at mod.chiselsandbits.client.model.baked.DataAwareChiseledBlockBakedModel.getModelData(DataAwareChiseledBlockBakedModel.java:89) ~[chiselsandbits:?] {re:classloading}
  at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:48) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
-- Block being tesselated --
Details:
  Block: Block{chiselsandbits:chiseledwood}[full_block=false]
  Block location: World: (-89,70,-233), Chunk: (at 7,4,7 in -6,-15; contains blocks -96,0,-240 to -81,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Stacktrace:
  at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:63) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:527) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:449) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender.func_228936_k_(ChunkRenderDispatcher.java:383) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.func_228902_a_(ChunkRenderDispatcher.java:164) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.WorldRenderer.func_228437_a_(WorldRenderer.java:847) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.WorldRenderer.func_228426_a_(WorldRenderer.java:936) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.WorldRendererAccess,pl:mixin:APP:immersiveengineering.mixins.json:coremods.client.WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}

-- Affected level --
Details:
  All players: 1 total; [ClientPlayerEntity['czarcipomiot'/2356, l='ClientLevel', x=-87.53, y=70.00, z=-230.80]]
  Chunk stats: Client Chunk Cache: 729, 467
  Level dimension: minecraft:overworld
  Level spawn location: World: (-48,67,-16), Chunk: (at 0,4,0 in -3,-1; contains blocks -48,0,-16 to -33,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
  Level time: 1072840 game time, 3728 day time
  Server brand: forge
  Server type: Non-integrated multiplayer server
Stacktrace:
  at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:classloading,xf:fml:xaerominimap:xaero_clientworldclass,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
  at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271] {}
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_271] {}
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_271] {}
  at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_271] {}
  at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
  at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
  at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
  Minecraft Version: 1.16.4
  Minecraft Version ID: 1.16.4
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_271, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3257488304 bytes (3106 MB) / 4294967296 bytes (4096 MB) up to 8388608000 bytes (8000 MB)
  CPUs: 8
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8000M -Xms4096M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  ModLauncher: 8.0.9+86+master.3cf110c
  ModLauncher launch target: fmlclient
  ModLauncher naming: srg
  ModLauncher services: 
    /mixin-0.8.2.jar mixin PLUGINSERVICE 
    /eventbus-4.0.0.jar eventbus PLUGINSERVICE 
    /forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
    /forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
    /accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
    /forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
    /forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
    /mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
    /forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
  FML: 35.1
  Forge: net.minecraftforge:35.1.37
  FML Language Providers: 
    javafml@35.1
    minecraft@1
  Mod List: 
    forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
    useful_backpacks-1.16.4-1.11.6.86.jar             |Useful Backpacks              |usefulbackpacks               |1.11.6.86           |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
    swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
    TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |NOSIGNATURE
    NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |NOSIGNATURE
    ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
    SilentLib-1.16.3-4.9.0+63.jar                     |Silent Lib                    |silentlib                     |4.9.0+63            |DONE      |NOSIGNATURE
    dungeons_plus-1.16.4-1.1.1.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.1               |DONE      |NOSIGNATURE
    SilentGear-1.16.3-2.5.1+206.jar                   |Silent Gear                   |silentgear                    |2.5.1+206           |DONE      |NOSIGNATURE
    jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
    reap-1.16.4-1.0.3.jar                             |Reap Mod                      |reap                          |1.16.4-1.0.3        |DONE      |NOSIGNATURE
    Xaeros_Minimap_21.0.0_Forge_1.16.4.jar            |Xaero's Minimap               |xaerominimap                  |21.0.0              |DONE      |NOSIGNATURE
    Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |DONE      |NOSIGNATURE
    gravestone-1.16.4-1.0.8.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.8        |DONE      |NOSIGNATURE
    ftb-backups-2.1.1.6.jar                           |FTB Backups                   |ftbbackups                    |2.1.1.6             |DONE      |NOSIGNATURE
    Clumps-6.0.0.13.jar                               |Clumps                        |clumps                        |6.0.0.13            |DONE      |NOSIGNATURE
    CookingForBlockheads_1.16.3-9.2.2 (1).jar         |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |DONE      |NOSIGNATURE
    tumbleweed-1.16-0.4.9.jar                         |Tumbleweed                    |tumbleweed                    |1.16-0.4.9          |DONE      |NOSIGNATURE
    guardvillagers-1.16.4-1.1.8.jar                   |Guard Villagers               |guardvillagers                |1.1.8               |DONE      |NOSIGNATURE
    u_team_core-1.16.4-3.1.17.191.jar                 |U Team Core                   |uteamcore                     |3.1.17.191          |DONE      |f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
    constructionwand-1.16.2-1.7.jar                   |Construction Wand             |constructionwand              |1.16.2-1.7          |DONE      |NOSIGNATURE
    Morpheus-1.16.4-4.2.68.jar                        |Morpheus                      |morpheus                      |4.2.68              |DONE      |NOSIGNATURE
    ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |DONE      |NOSIGNATURE
    forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
    AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
    chiselsandbits-0.2.9-RELEASE.jar                  |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
    structure_gel-1.16.4-1.7.4.jar                    |Structure Gel API             |structure_gel                 |1.7.4               |DONE      |NOSIGNATURE
  Crash Report UUID: ab727c9d-6916-4a66-9837-deddce2bdb81
  Launched Version: 1.16.4
  Backend library: LWJGL version 3.2.2 build 10
  Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.89, NVIDIA Corporation
  GL Caps: Using framebuffer using OpenGL 3.0
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'forge'
  Type: Client (map_client.txt)
  Graphics mode: fast
  Resource Packs: 
  Current Language: English (US)
  CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
[13:54:36] [Render thread/INFO] [STDOUT/]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\izabela\AppData\Roaming\Crystal-Launcher\instances\u.xxx12\.minecraft\saves\fffo\instances\u.16.4_server_or_single\.minecraft\crash-reports\crash-2021-01-16_13.54.36-client.txt

* MC Version: 1.16.4
* C&B Version: chiselsandbits-0.2.9-RELEASE
* Do You have Optifine: No

**Comment by khan-22** [comment]
I was about to make an issue on this but this seems to be the same so I'll just post my information here.

* MC Version: 1.16.4
* C&B Version: 0.2.9
* Do You have Optifine: No

I disabled all other mods for this.

While investigating #583 I tried to do as many actions as possible with C&B as I could repeatedly and came across a fairly consistent crash. It happens to me every time I hold right click to spam horizontal planes so that they stack up towards a full block (So I don't think it's only 'draw region' that is doing this). The crash seems to happen at any time I place a plane. It could be the second plane, or the 15th. But it happens fairly consistently for me when I try it in a recently created superflat creative world (desert preset).

Here's my log output
[crash-2021-01-16_20.30.52-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/5825040/crash-2021-01-16_20.30.52-client.txt)

**Comment by czarcipomiot** [comment]
After some tests single player crash too when i put down too many chiseled blocks. But problem with draw region have place only on Mp

**Comment by ninjaz5736** [comment]
Just had this crash, [here](https://pastebin.com/uic1T1mt)'s my client log for what it's worth but it seems similar to others, I was using other mods too (seen in the log) but everything seems related to C&B. Happened just as I "recompleted" a grass block, using the single bit mode, and having just removed a few bits I put them back. The block seemed to re-render for a split second before the client crashed (exit code 255, "message The game crashed whilst tesselating block in world"), the server log just showed disconnected:

```
[Server thread/INFO] [minecraft/ServerPlayNetHandler]: ninjaz5736 lost connection: Disconnected
[Server thread/INFO] [minecraft/DedicatedServer]: ninjaz5736 left the game
```

- MC Version: 1.16.4
- C&B Version: 0.2.9
- Do You have Optifine: Yes
- Mode: Multiplayer

On a positive note, the off-by-one-bit positioning bug seems to be fixed!
