### ISSUE TITLE
Every chiseled Block disappears and heavy lags after updating to version 0.3.2-RELEASE

### ISSUE THREAD

**Issue by hodo1962** [ChiselsAndBits/Chisels-and-Bits#633]
After updating from 0.3.1-RELEASE to version 0.3.2-RELEASE every chiseled block in existing worlds disappeared.
Chiseling any blocks causes heavy lags.
I've reinstalled version 0.3.1-RELEASE and the disappered blocks reappeared and there were no more lags.

For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.2-RELEASE
* Do You have Optifine: yes

**Comment by Sudo-Stefano** [comment]
i have the same issue, reinstalled 0.3.1 version no problems at all.

**Comment by TheMorgander** [comment]
Can confirm for version 0.2.9-RELEASE to 0.3.2-RELEASE.

`[08Mar2021 15:52:11.225] [Worker-Main-10/ERROR] [chiselsandbits/]: Unable to read blob.
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Lnet.minecraft.block.BlockState;
	at mod.chiselsandbits.utils.PaletteUtils.read(PaletteUtils.java:61) ~[?:?]
	at mod.chiselsandbits.chiseledblock.serialization.PalettedBlobSerializer.<init>(PalettedBlobSerializer.java:49) ~[?:?]
	at mod.chiselsandbits.chiseledblock.data.VoxelBlob.read(VoxelBlob.java:1057) ~[?:?]
	at mod.chiselsandbits.chiseledblock.data.VoxelBlob.blobFromBytes(VoxelBlob.java:1026) ~[?:?]
	at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlobCatchable(VoxelBlobStateInstance.java:105) ~[?:?]
	at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlob(VoxelBlobStateInstance.java:89) [?:?]
	at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateReference.getVoxelBlob(VoxelBlobStateReference.java:105) [?:?]
	at mod.chiselsandbits.render.chiseledblock.ChiseledBlockSmartModel.getCachedModel(ChiseledBlockSmartModel.java:79) [?:?]
	at mod.chiselsandbits.client.model.baked.DataAwareChiseledBlockBakedModel.getModelData(DataAwareChiseledBlockBakedModel.java:111) [?:?]
	at net.minecraft.client.renderer.BlockModelRenderer.renderModel(BlockModelRenderer.java:82) [?:?]
	at net.minecraft.client.renderer.BlockRendererDispatcher.renderModel(BlockRendererDispatcher.java:83) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_228940_a_(ChunkRenderDispatcher.java:907) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$ChunkRender$RebuildTask.func_225618_a_(ChunkRenderDispatcher.java:734) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher.lambda$runTask$1(ChunkRenderDispatcher.java:191) [?:?]
	at net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$$Lambda$6527/147901726.apply(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1624) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]`

**Comment by marchermans** [comment]
Should be fixed in 0.3.3
