### ISSUE TITLE
1.16.5 server crash (FTB Endeavour)

### ISSUE THREAD

**Issue by skerit** [ChiselsAndBits/Chisels-and-Bits#653]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4
* Do You have Optifine: No, but it's a server-side crash anyway

Server was running fine. Today was the first day anyone used the chisel & bits mod, and it seemed to go ok. But then this happened, which froze the entire server:

```
[02:09:06] [Server thread/ERROR] [chiselsandbits/]: Unable to find TileEntity while interacting with block.
java.lang.Exception: null
        at mod.chiselsandbits.core.Log.noTileError(Log.java:39) ~[chiselsandbits:?] {re:classloading}
        at mod.chiselsandbits.chiseledblock.BlockChiseled.func_196253_a(BlockChiseled.java:118) ~[chiselsandbits:?] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_196953_a(AbstractBlock.java:665) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:starlight.mixins.json:common.blockstate.AbstractBlockStateMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.item.BlockItemUseContext.func_196011_b(SourceFile:60) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.item.BlockItem.func_195942_a(BlockItem.java:44) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.item.BlockItem.func_195939_a(BlockItem.java:39) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:BlockItemMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:643) ~[forge:?] {re:classloading}
        at net.minecraft.item.ItemStack.func_196084_a(ItemStack.java:187) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:astralsorcery:add_missing_tag_enchantment_tooltip,xf:fml:astralsorcery:add_enchantment_tooltip,xf:fml:forge:filled_map.4,xf:fml:forge:itemstack,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:353) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282] {}

```

**Comment by skerit** [comment]
Afterwards I was unable to actually successfully restart the server, it always got stuck at the "Saving chunks" stage.
So I disabled Chisels-and-Bits, restarted it again (which made it remove the offending broken blocks), enabled it again, and now it starts back up.

**Comment by glarmer** [comment]
I am having a similar issue, however I get no exception.

A user uses chisels and bits and as a result the server cannot load whilst it has that region loaded. Deleting the region or chisels and bits allows the server to restart but reintroducing chisels and bits prevents it.

For clarity, when I say the server can't start, it starts but goes fully unresponsive once the chunk is loaded (which in modded with chunkloaders is more often than not)

Another observation is that this doesn't always happen. In my region I had a simple chiselled block or two where it was a 1*1*16 (1 chisel block thin panel) and it was fine for a long period, but once I started building complex chiselled content, problems arose

I'd like to note this is present in AT LEAST 2.10 up to 3.4 as I've tested to see.

**Comment by glarmer** [comment]
Oh also, I am using a custom modpack, forge 36.0.39

Abnormals core
Akashic Tome
AppleSkin
Applied Energistics 2
Architect's Palette
Architectury Forge
Ars Nouveau
Astral Sorcery
Aurum's More Blocks (AMB)
AutoRegLib
Better Animals Plus
Biomes O Plenty
Chisels & Bits
Chocolate Fix
Citadel
Clumps
Code Chicken Library
COFH Core
Computer Craft: Tweaked
Controlling
Cooking for blockheads
Corpse
Create
Creatures and Beasts
Crossroads
Curios
Decorative Blocks
Decorative Winter
Doggy Talents
Druidcraft
Dungeon crawl
Dynamic Surroundings
Eidolon
Ender Storage
Essentials
Extended Caves
Extreme Reactors
FakeBlocks
FallingTree
Fast furnace
Fast workbench
FerriteCore
FTB Chunks
FTB GUI library
FTB Teams
Futurepack
Geckolib
Guide-API-VP
Ice and Fire: Dragons
Infernal expansion
Jade
Joy of Painting
Just Enough items
KleeSlabs
Ma's Essentials
Mana and artifice
Mekanism
mgui
MineColonies
Mystical World
Nature's Compass
ObserverLib
Occultism
Oh The Biomes You'll Go
Pams Harvestcraft: Crops
Pams Harvestcraft: Food Core
Pams Harvestcraft: Food Extended
Pams Harvestcraft: Trees
Patchouli
Performant
Placebo
PneumaticCraft: Repressurized
Polymorph
PSI
Quark
Quark Oddities
Random Patches
Repurposed Structures
Simple voice chat
Starlight
Storage drawers
Structurize
Terraforged
Tetra
The weirding gadget
Thermal Expansion
Thermal Foundation
Travelers Backpack
Traversed Reforge
Upgrade aquatic
V-Tweaks
Valhelsia Structures
Vampirism
Waystones
When dungeons arise
Wordedit
Yung's API
YUNG's Better Caves
YUNG's Better Mineshafts
Zero core

**Comment by LordNoisy** [comment]
Abnormals core
Akashic Tome
AppleSkin
Applied Energistics 2
Architect's Palette
Architectury Forge
Ars Nouveau
Astral Sorcery
Aurum's More Blocks (AMB)
AutoRegLib
Better Animals Plus
Biomes O Plenty
Chisels & Bits
Chocolate Fix
Citadel
Clumps
Code Chicken Library
COFH Core
Computer Craft: Tweaked
Controlling
Cooking for blockheads
Corpse
Create
Creatures and Beasts
Crossroads
Curios
Decorative Blocks
Decorative Winter
Doggy Talents
Druidcraft
Dungeon crawl
Dynamic Surroundings
Eidolon
Ender Storage
Essentials
Extended Caves
Extreme Reactors
FakeBlocks
FallingTree
Fast furnace
Fast workbench
FerriteCore
FTB Chunks
FTB GUI library
FTB Teams
Futurepack
Geckolib
Guide-API-VP
Ice and Fire: Dragons
Infernal expansion
Jade
Joy of Painting
Just Enough items
KleeSlabs
Ma's Essentials
Mana and artifice
Mekanism
mgui
MineColonies
Mystical World
Nature's Compass
ObserverLib
Occultism
Oh The Biomes You'll Go
Pams Harvestcraft: Crops
Pams Harvestcraft: Food Core
Pams Harvestcraft: Food Extended
Pams Harvestcraft: Trees
Patchouli
Performant
Placebo
PneumaticCraft: Repressurized
Polymorph
PSI
Quark
Quark Oddities
Random Patches
Repurposed Structures
Simple voice chat
Starlight
Storage drawers
Structurize
Terraforged
Tetra
The weirding gadget
Thermal Expansion
Thermal Foundation
Travelers Backpack
Traversed Reforge
Upgrade aquatic
V-Tweaks
Valhelsia Structures
Vampirism
Waystones
When dungeons arise
Wordedit
Yung's API
YUNG's Better Caves
YUNG's Better Mineshafts
Zero core
