### ISSUE TITLE
C&B Blocks disappear when Placed on a Mohist Server

### ISSUE THREAD

**Issue by JustDoinGoodForMe** [ChiselsAndBits/Chisels-and-Bits#677]
For any bug reports please provide the following details as well,
* MC Version: 1.16.5
* C&B Version: 0.3.4 Release
* Do You have Optifine: No

So i am Hosting a Mohist server(Forge+Spigot) and i have heard Complains that the C&B Bits/Buildings just disappear and after some time they are given in the Inventory again.

Also i get this Message in the Logs:
[10:10:54 ERROR]: Unable to read blob.
java.io.EOFException: Unexpected end of ZLIB input stream
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245) ~[?:?]
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159) ~[?:?]
at mod.chiselsandbits.chiseledblock.data.VoxelBlob.read(VoxelBlob.java:1041) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.data.VoxelBlob.blobFromBytes(VoxelBlob.java:1026) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlobCatchable(VoxelBlobStateInstance.java:105) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlob(VoxelBlobStateInstance.java:89) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateReference.getVoxelBlob(VoxelBlobStateReference.java:105) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.NBTBlobConverter.getBlob(NBTBlobConverter.java:275) ~[chiselsandbits:?]
at mod.chiselsandbits.helpers.ModUtil.getBlobFromStack(ModUtil.java:423) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.ItemBlockChiseled.tryPlaceBlockAt(ItemBlockChiseled.java:246) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.ItemBlockChiseled.placeBitBlock(ItemBlockChiseled.java:220) ~[chiselsandbits:?]
at mod.chiselsandbits.chiseledblock.ItemBlockChiseled.tryPlace(ItemBlockChiseled.java:508) ~[chiselsandbits:?]
at mod.chiselsandbits.network.packets.PacketAccurateSneakPlace.server(PacketAccurateSneakPlace.java:86) ~[chiselsandbits:?]
at mod.chiselsandbits.network.ModPacket.processPacket(ModPacket.java:46) ~[chiselsandbits:?]
at mod.chiselsandbits.network.NetworkChannel.lambda$null$1(NetworkChannel.java:66) ~[chiselsandbits:?]
at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:217) ~[forge:?]
at mod.chiselsandbits.network.NetworkChannel.lambda$registerMessage$2(NetworkChannel.java:66) ~[chiselsandbits:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:90) ~[forge:?]
at java.util.Optional.map(Optional.java:265) ~[?:?]
at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:90) ~[forge:?]
at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2602) ~[?:?]
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26) ~[?:?]
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:136) ~[?:?]
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:880) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:109) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:863) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:857) ~[?:?]
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:119) ~[?:?]
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:843) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:763) ~[?:?]
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]

Is there any Way to fix this ?

**Comment by marchermans** [comment]
Not something I can sadly support.
For some reason your server is messing with the packets and causing them to wrongly uncompress the bit data.

I don't know what could the cause of that be, nor do I know how to fix that sorry.


That said there is a massive rework ongoing that might or might not fix this.

**Comment by marchermans** [comment]
Try the newest beta. Else i have no option but to defer you to the mohist guys.
