### ISSUE TITLE
There was a severe problem during mod loading that has caused the game to fail

### ISSUE THREAD

**Issue by jrydert** [ChiselsAndBits/Chisels-and-Bits#758]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390 (3).jar)
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_21.8.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 10/11/21 4:05 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from XRay (xray)
Caused by: java.lang.NullPointerException
	at com.xray.common.config.ConfigHandler.setup(ConfigHandler.java:66)
	at com.xray.common.XRay.preInit(XRay.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1138826144 bytes (1086 MB) / 2147483648 bytes (2048 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 28 mods loaded, 28 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                 | Source                                            | Signature                                |
	|:----- |:-------------------- |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                  | minecraft.jar                                     | None                                     |
	| LCH   | mcp                  | 9.42                    | minecraft.jar                                     | None                                     |
	| LCH   | FML                  | 8.0.99.99               | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2855            | forge-1.12.2-14.23.5.2855.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | xaerominimap_core    | 1.12.2-1.0              | minecraft.jar                                     | None                                     |
	| LCH   | damageindicatorsmod  | 1.0                     | [1.12.2]DamageIndicatorsMod-3.5.1.jar             | None                                     |
	| LCH   | jei                  | 4.16.1.301              | jei_1.12.2-4.16.1.301.jar                         | None                                     |
	| LCH   | appleskin            | 1.0.14                  | AppleSkin-mc1.12-1.0.14.jar                       | None                                     |
	| LCH   | backpack             | 3.0.2                   | Backpacks-Mod-1.12.2.jar                          | None                                     |
	| LCH   | durabilityviewer     | 1.6                     | DurabilityViewer-1.12-forge14.21.1.2387-1.6.jar   | None                                     |
	| LCH   | umm3185118519        | release 1.5 - MC 1.12.2 | Extended+ItemsOres+[1.12.2]+(release+1.5) (1).jar | None                                     |
	| LCH   | fasterladderclimbing | 0.1-146                 | FasterLadderClimbing-1.12-0.1-146.jar             | None                                     |
	| LCH   | flansmod             | 5.10.0                  | Flans+Mod-1.12.2-5.10.0 (1).jar                   | None                                     |
	| LCH   | llibrary             | 1.7.20                  | llibrary-1.7.20-1.12.2.jar                        | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | fossil               | 8.0.5                   | fossilsarcheology-8.0.5 (4).jar                   | None                                     |
	| LCH   | gravestone           | 1.10.2                  | gravestone-1.10.2 (1).jar                         | None                                     |
	| LCH   | mts                  | 19.15.7                 | Immersive+Vehicles-1.12.2-19.15.7 (2).jar         | None                                     |
	| LCH   | ic2                  | 2.8.170-ex112           | industrialcraft-2-2.8.170-ex112 (2).jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | ironchest            | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847 (2).jar               | None                                     |
	| LCH   | journeymap           | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1 (1).jar                   | None                                     |
	| LCH   | jeresources          | 0.9.2.60                | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
	| LCH   | llor                 | 1.1.6-mc1.12.2          | LLOverlayReloaded-1.1.6-mc1.12.2.jar              | None                                     |
	| LCH   | mekanism             | 1.12.2-9.8.3.390        | Mekanism-1.12.2-9.8.3.390 (3).jar                 | None                                     |
	| LCH   | mekanismgenerators   | 1.12.2-9.8.3.390        | MekanismGenerators-1.12.2-9.8.3.390.jar           | None                                     |
	| LCH   | mw                   | 1.11.7.7                | mw-1.11.7.7_mc1.12.2.jar                          | None                                     |
	| LCH   | parachutemod         | 1.7.4                   | parachutemod-1.12.2-1.7.4-446.jar                 | None                                     |
	| LCH   | xaerominimap         | 21.8.0                  | Xaeros_Minimap_21.8.0_Forge_1.12.jar              | None                                     |
	| LCE   | xray                 | 1.4.0                   | xray-1.12.2-1.4.2.jar                             | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MekanismCoremod (Mekanism-1.12.2-9.8.3.390 (3).jar)
  mekanism.coremod.KeybindingMigrationHelper
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_21.8.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.41' Renderer: 'NVIDIA GeForce RTX 3060/PCIe/SSE2'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.41
	OpenGlRenderer: NVIDIA GeForce RTX 3060/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16

**Comment by marchermans** [comment]
This has nothing todo with C&B.
Closing
