### ISSUE TITLE
Error in Log/Console in version 9.21 for 1.9.

### ISSUE THREAD

**Issue by FusionLord** [ChiselsAndBits/Chisels-and-Bits#77]
This prints to Log/Console when on the clipboard tab, NOTE: The clipboard items were made in 1.9.4 - 1.10

``` Java
[03:01:46] [Client thread/ERROR] [chiselsandbits]: Unable to read blob.
java.lang.RuntimeException: Invalid Version: 2
    at mod.chiselsandbits.chiseledblock.data.VoxelBlob.read(VoxelBlob.java:947) ~[VoxelBlob.class:?]
    at mod.chiselsandbits.chiseledblock.data.VoxelBlob.blobFromBytes(VoxelBlob.java:912) ~[VoxelBlob.class:?]
    at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateInstance.getBlob(VoxelBlobStateInstance.java:89) [VoxelBlobStateInstance.class:?]
    at mod.chiselsandbits.chiseledblock.data.VoxelBlobStateReference.getVoxelBlob(VoxelBlobStateReference.java:103) [VoxelBlobStateReference.class:?]
    at mod.chiselsandbits.chiseledblock.NBTBlobConverter.updateFromBlob(NBTBlobConverter.java:192) [NBTBlobConverter.class:?]
    at mod.chiselsandbits.client.CreativeClipboardTab.displayAllRelevantItems(CreativeClipboardTab.java:115) [CreativeClipboardTab.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.setCurrentCreativeTab(GuiContainerCreative.java:501) [GuiContainerCreative.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.mouseReleased(GuiContainerCreative.java:470) [GuiContainerCreative.class:?]
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:627) [GuiScreen.class:?]
    at net.minecraft.client.gui.inventory.GuiContainerCreative.handleMouseInput(GuiContainerCreative.java:593) [GuiContainerCreative.class:?]
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:583) [GuiScreen.class:?]
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1791) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1114) [Minecraft.class:?]
    at net.minecraft.client.Minecraft.run(Minecraft.java:401) [Minecraft.class:?]
    at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_45]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45]
    at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
    at GradleStart.main(GradleStart.java:26) [start/:?]
```

**Comment by AlgorithmX2** [comment]
Delete your clipboard or return to the latest build of C&B.

The newest version uses version 2 you must be using a clipboard from the latest builds on an older build.

**Comment by FusionLord** [comment]
Yes, wasn't sure if that was the issue, just wanted to check :)
