### ISSUE TITLE
Crashing game when using change tool type gui

### ISSUE THREAD

**Issue by Ruckius** [ChiselsAndBits/Chisels-and-Bits#791]
Game crashes every time the button tied to the tool type is pressed. 

For any bug reports please provide the following details as well,
* MC Version: 16.5
* C&B Version:1.0.43
* Do You have Optifine: Happens with and without Optifine

crash report: java.lang.NullPointerException: Unexpected error
	at mod.chiselsandbits.client.screens.widgets.ToolModeSelectionWidget.init(ToolModeSelectionWidget.java:151) ~[?:1.0.43] {re:classloading}
	at mod.chiselsandbits.api.client.screen.AbstractChiselsAndBitsScreen.func_230481_d_(AbstractChiselsAndBitsScreen.java:51) ~[?:1.0.43] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.func_230480_a_(Screen.java:107) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at mod.chiselsandbits.api.client.screen.AbstractChiselsAndBitsScreen.func_230480_a_(AbstractChiselsAndBitsScreen.java:43) ~[?:1.0.43] {re:classloading}
	at mod.chiselsandbits.client.screens.ToolModeSelectionScreen.func_231160_c_(ToolModeSelectionScreen.java:47) ~[?:1.0.43] {re:classloading}
	at net.minecraft.client.gui.screen.Screen.func_231158_b_(Screen.java:325) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:quark.mixins.json:client.ScreenMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at mod.chiselsandbits.keys.KeyBindingManager.handleKeyPresses(KeyBindingManager.java:122) ~[?:1.0.43] {re:classloading}
	at mod.chiselsandbits.keys.KeyBindingManager.handleClientTickEvent(KeyBindingManager.java:103) ~[?:1.0.43] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_656_KeyBindingManager_handleClientTickEvent_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2595/714402061.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPreClientTick(BasicEventHooks.java:105) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1414) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mining_helmet.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.0.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$457/230266757.call(Unknown Source) [forge-1.16.5-36.2.0.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

**Comment by Talia-12** [comment]
I've also experienced this (stack trace [here](https://paste.ee/p/JWhcX))

**Comment by DasBean125** [comment]
Having identical issues as well, unsure about how many of the tools supporting that GUI do this, so far it only seems to be the pattern that is the culprit (for me at least)

**Comment by marchermans** [comment]
Fixed in the 1.18 update.
