### ISSUE TITLE
Crash on 1.18.1 with only Chisel & Bits + Fabric API

### ISSUE THREAD

**Issue by ShaneTRS** [ChiselsAndBits/Chisels-and-Bits#803]
Game log:
```
[09:38:41] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[09:38:41] [main/INFO]: Loading 49 mods:
	- chiselsandbits 1.2.56
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
Exiting with -1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod chiselsandbits
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 11 more
Process exited with code 255.
```

All version info provided in log

I think the source of the problem is that the dev jar was the one released, not the standard one lol

**Comment by ftzi** [comment]
Same.

```
[21:35:37] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[21:35:37] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[21:35:53] [main/INFO]: Dependencies overridden for fabric, antighost, advancementinfo, dcch, colormatic
[21:35:53] [main/INFO]: Loading 142 mods:
	- advanced_runtime_resource_pack 0.5.4 via enhancedblockentities
	- advancementinfo 1.18-fabric0.43.1-1.3
	- animatica 0.2+1.18
	- antighost 1.18-fabric0.43.1-1.1.4
	- architectury 3.2.60
	- autoconfig1u 3.2.2 via capes
	- bettermounthud 1.1.3
	- borderlessmining 1.1.1+1.18
	- capes 1.2.2+1.18
	- cardinal-components-base 4.0.1 via xp_storage
	- cardinal-components-entity 4.0.1 via xp_storage
	- cardinal-components-item 4.0.1 via xp_storage
	- cem 0.7.0
	- chiselsandbits 1.2.56
	- citresewn 0.8.1-1.18
	- cleancut 1.18-4.0-fabric
	- cloth-api 2.0.54
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-client-events-v0 2.0.54 via cloth-api
	- cloth-common-events-v1 2.0.54 via cloth-api
	- cloth-config 6.1.48
	- cloth-datagen-api-v1 2.0.54 via cloth-api
	- cloth-scissors-api-v1 2.0.54 via cloth-api
	- cloth-utils-v1 2.0.54 via cloth-api
	- colormatic 2.4.0+mc.1.18
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- comforts 1.0.0-1.18
	- completeconfig 1.3.3
	- continuity 1.0.3+1.18
	- crowdin-translate 1.4+1.18 via antighost
	- cullleaves 2.3.2
	- dcch 1.0
	- dynamicfps 2.0.6
	- enhancedblockentities 0.5+1.18
	- entityculling 1.3.3
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd14 via sodium
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9514 via citresewn
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.8+c8aba2f365 via fabric
	- fabric-keybindings-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.3+3ac43d9565 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-renderer-api-v1 0.4.9+3ac43d9565 via fabric
	- fabric-renderer-indigo 0.4.12+3ac43d9565 via fabric
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.9+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.3+6b21378a65 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9514 via borderlessmining
	- fabric-screen-api-v1 1.0.7+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-textures-v0 1.0.9+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fabrishot 1.6.0
	- fallingtree 3.0.0
	- fastopenlinksandfolders 1.0.0
	- ferritecore 4.0.0
	- firstperson 2.1.0
	- grindenchantments 1.5.0+1.18
	- illuminations 1.10.2
	- imm_ptl_core 1.1.7 via immersive_portals
	- immersive_portals 1.1.7
	- incantationem 1.1.3+1.18.1
	- indium 1.0.2-alpha1+mc1.18
	- inmis 2.4.0-1.18
	- iris 1.1.3
	- itemmodelfix 1.0.3+1.18
	- java 17
	- lambdabettergrass 1.2.1+1.17
	- lambdynlights 2.1.0+1.17
	- languagereload 1.2
	- lazydfu 0.1.2
	- lithium 0.7.6
	- midnightlib 0.2.9 via cullleaves
	- minecraft 1.18.1
	- mm 2.1 via slight-gui-modifications
	- modmenu 3.0.1
	- morechathistory 1.1.0
	- no-telemetry 1.3.0
	- nofade 1.18-2.0.1
	- notenoughanimations 1.4.0
	- notenoughcrashes 4.1.3+1.18
	- omega-config 1.0.8 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_aperlambda_lambdajcommon 1.8.1 via spruceui
	- org_codehaus_groovy_groovy 3.0.8 via slight-gui-modifications
	- org_codehaus_groovy_groovy-jsr223 3.0.8 via slight-gui-modifications
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_slf4j_slf4j-api 1.7.12 via iris
	- pride 1.1.0+1.17 via lambdynlights
	- q_misc_util 1.1.7 via immersive_portals
	- reeses-sodium-options 1.2.3
	- roughlyenoughitems 7.1.357
	- skinlayers 1.3.1
	- slight-gui-modifications 2.0.2
	- smoothboot 1.18-1.7.0
	- sodium 0.4.0-alpha5+build.9
	- sodium-extra 0.3.7
	- spruceui 3.3.0+1.17 via lambdynlights
	- starlight 1.0.0+fabric.d0a3220
	- tooltipfix 1.0.4-1.18
	- wi_zoom 1.3-MC1.18.1
	- xp_storage 1.4.3+1.18
	- yosbr 0.1.1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod chiselsandbits
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	... 8 more
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 11 more
Process exited with code 255.
```

**Comment by ShaneTRS** [comment]
Confirmed my suspicions, the `dev` jar was uploaded to CurseForge by mistake. Building it manually and using the regular jar fixes the crash.

**Comment by marchermans** [comment]
Yeah, CI has the wrong target jar to upload, I fixed that in the build that will appear today.
