### ISSUE TITLE
ChiselsBits-fabric-1.18.1-1.2.57-dev Crashing Minecraft at Boot

### ISSUE THREAD

**Issue by RotokEralil** [ChiselsAndBits/Chisels-and-Bits#805]
Crashes when I press play.

Before continuing if you are reporting an issue, please ensure that all mods involved are updated to the latest version available, if your issue with with intermod compatibility such mixing C&B bits with other blocks make sure that MCMP is also updated. If your issue is a crash, be sure to include the crash log with your report.

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: ChiselsBits-fabric-1.18.1-1.2.57-dev
* Fabric Loader: 0.12.12-1.18.1
* Do You have Optifine: No
Copy Stack

* java.lang.RuntimeException: Failed to read accessWidener file from mod chiselsandbits
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:145)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:281)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:90)
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478)
	... 3 more

**Comment by marchermans** [comment]
Fixed in 1.2.58
