### ISSUE TITLE
Cannot send packets when not in game

### ISSUE THREAD

**Issue by genDevo** [ChiselsAndBits/Chisels-and-Bits#815]
* MC Version: 1.18.1 Fabric
* C&B Version: 1.2.62
* Do You have Optifine: No

Was trying to change the redo/undo keybinds in the main menu and got this. Also both of those keybinds visually say they require ctrl to be held but activate whenever the key is just pressed, including while typing in chat or a text field.
```
---- Minecraft Crash Report ----
// There are four lights!

Time: 1/3/22, 11:03 AM
Description: Unexpected error

java.lang.IllegalStateException: Cannot send packets when not in game!
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking.send(ClientPlayNetworking.java:228)
	at mod.chiselsandbits.fabric.platform.network.FabricNetworkChannel.lambda$sendToServer$2(FabricNetworkChannel.java:72)
	at mod.chiselsandbits.platforms.core.dist.DistExecutor.unsafeRunWhenOn(DistExecutor.java:101)
	at mod.chiselsandbits.platforms.core.dist.DistExecutor.runWhenOn(DistExecutor.java:85)
	at mod.chiselsandbits.fabric.platform.network.FabricNetworkChannel.sendToServer(FabricNetworkChannel.java:64)
	at mod.chiselsandbits.network.NetworkChannel.sendToServer(NetworkChannel.java:95)
	at mod.chiselsandbits.keys.KeyBindingManager.handleKeyPresses(KeyBindingManager.java:188)
	at mod.chiselsandbits.fabric.client.FabricChiselsAndBitsClient.lambda$setupEvents$4(FabricChiselsAndBitsClient.java:103)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$bib000$onStartTick(class_310.java:8992)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1086)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by marchermans** [comment]
Closed in #825 released in 1.2.65
