### ISSUE TITLE
Server crashes. Probably conflict with Create.

### ISSUE THREAD

**Issue by frikinjay** [ChiselsAndBits/Chisels-and-Bits#824]
There is no crash report but this in the logs. There was a recent conflict with Create but was supposedly fixed yesterday i am guessing this is related. Using the 0.4b build of Create Fabric. [This](https://github.com/Fabricators-of-Create/Create/issues/72) issue.

```
[main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1309 failed
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector redirectGetBlockFriction(Lnet/minecraft/class_2248;)F in chiselsandbits.mixins.json:platform.world.entity.LivingEntityWorldlyBlockMixin from mod chiselsandbits failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Chisels&Bits-fabric-1.18.1-refmap.json
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.10.7+mixin.0.8.4.jar:0.10.7+mixin.0.8.4]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.12.12.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.minecraft.class_2246.<clinit>(class_2246.java:103) ~[server-intermediary.jar:?]
        at net.minecraft.class_5872.<clinit>(class_5872.java:9) ~[server-intermediary.jar:?]
        at net.minecraft.class_5871.method_33968(class_5871.java:16) ~[server-intermediary.jar:?]
        at com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76) ~[datafixerupper-4.0.26.jar:?]
        at net.minecraft.class_5871.<clinit>(class_5871.java:12) ~[server-intermediary.jar:?]
        at net.minecraft.class_2939.<clinit>(class_2939.java:31) ~[server-intermediary.jar:?]
        at net.minecraft.class_5463.<clinit>(class_5463.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30572(class_5458.java:46) ~[server-intermediary.jar:?]
        at net.minecraft.class_5458.method_30566(class_5458.java:78) ~[server-intermediary.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at net.minecraft.class_5458.<clinit>(class_5458.java:77) ~[server-intermediary.jar:?]
        at net.minecraft.class_2378.<clinit>(class_2378.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2966.method_12851(class_2966.java:49) ~[server-intermediary.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) ~[server-intermediary.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
        ... 7 more
```

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.62
* Do You have Optifine: No

**Comment by marchermans** [comment]
As create does not exist for fabric i highly doubt it...

Are you using any rendering engine like canvas?

**Comment by frikinjay** [comment]
Doesnt exist on curseforge yet but [here](https://github.com/Fabricators-of-Create/Create). You can compile it if you want, i tried it with the latest build.

**Comment by marchermans** [comment]
Yeah no, I won't support an unofficial mod which I have to compile myself.... That won't be happening sorry.

**Comment by marchermans** [comment]
@frikinjay I fixed it anyway, because it was easy.
Will be in the next release.

**Comment by frikinjay** [comment]
@OrionDevelopment I dont know what you mean by not supporting an unofficial mod because this has been made with the original creators permission and in collab with them and will be on curseforge eventually. Of course its your choice at the end of the day so you do you.

**Comment by marchermans** [comment]
But it is not published nor is there any maven version i can properly test against.

How ever I did fix it I hope. At least this crash i did fix. Hopefully this was all that needed fixing

**Comment by frikinjay** [comment]
Yeah its fixed, thanks for that.
