### ISSUE TITLE
Crash while browsing REI

### ISSUE THREAD

**Issue by frikinjay** [ChiselsAndBits/Chisels-and-Bits#829]
```
Description: Rendering entry

java.lang.IllegalArgumentException: x (0) must be > 0
	at com.google.common.math.MathPreconditions.checkPositive(MathPreconditions.java:40)
	at com.google.common.math.LongMath.log2(LongMath.java:123)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.onPaletteResize(SimpleStateEntryStorage.java:311)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryPalette.deserializeNBT(SimpleStateEntryPalette.java:63)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:283)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:29)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.lambda$deserializeNBT$0(SingleBlockMultiStateItemStack.java:798)
	at mod.chiselsandbits.utils.GZIPDataCompressionUtils.decompress(GZIPDataCompressionUtils.java:60)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:797)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:791)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.lambda$deserializeNBT$1(LegacyVersionedStorageEngine.java:39)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.deserializeNBT(LegacyVersionedStorageEngine.java:39)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:51)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:11)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.deserializeNBT(SingleBlockMultiStateItemStack.java:432)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.<init>(SingleBlockMultiStateItemStack.java:71)
	at mod.chiselsandbits.item.ChiseledBlockItem.createItemStack(ChiseledBlockItem.java:52)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:62)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:237)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.render(ItemEntryDefinition.java:242)
	at me.shedaniel.rei.api.client.entry.renderer.ForwardingEntryRenderer.render(ForwardingEntryRenderer.java:42)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:196)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:283)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:125)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:290)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:608)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:506)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:341)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:63)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy3/jdk.proxy3.$Proxy142.render(Unknown Source)
	at net.minecraft.class_757.handler$zlf000$renderScreenPost(dev/architectury/mixin/fabric/client/MixinGameRenderer.java [architectury.mixins.json]:61)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.math.MathPreconditions.checkPositive(MathPreconditions.java:40)
	at com.google.common.math.LongMath.log2(LongMath.java:123)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.onPaletteResize(SimpleStateEntryStorage.java:311)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryPalette.deserializeNBT(SimpleStateEntryPalette.java:63)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:283)
	at mod.chiselsandbits.block.entities.storage.SimpleStateEntryStorage.deserializeNBT(SimpleStateEntryStorage.java:29)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.lambda$deserializeNBT$0(SingleBlockMultiStateItemStack.java:798)
	at mod.chiselsandbits.utils.GZIPDataCompressionUtils.decompress(GZIPDataCompressionUtils.java:60)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:797)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack$LegacyGZIPStorageBasedStorageHandler.deserializeNBT(SingleBlockMultiStateItemStack.java:791)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.lambda$deserializeNBT$1(LegacyVersionedStorageEngine.java:39)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at mod.chiselsandbits.storage.LegacyVersionedStorageEngine.deserializeNBT(LegacyVersionedStorageEngine.java:39)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:51)
	at mod.chiselsandbits.storage.LegacyAwareStorageEngine.deserializeNBT(LegacyAwareStorageEngine.java:11)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.deserializeNBT(SingleBlockMultiStateItemStack.java:432)
	at mod.chiselsandbits.item.multistate.SingleBlockMultiStateItemStack.<init>(SingleBlockMultiStateItemStack.java:71)
	at mod.chiselsandbits.item.ChiseledBlockItem.createItemStack(ChiseledBlockItem.java:52)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:62)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition$ItemEntryRenderer.getExtraData(ItemEntryDefinition.java:237)

-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
Stacktrace:
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.screen(CrashReportUtils.java:49)
	at me.shedaniel.rei.impl.client.util.CrashReportUtils.essential(CrashReportUtils.java:43)
	at me.shedaniel.rei.impl.common.entry.AbstractEntryStack.render(AbstractEntryStack.java:198)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.drawCurrentEntry(EntryWidget.java:313)
	at me.shedaniel.rei.impl.client.gui.widget.EntryWidget.method_25394(EntryWidget.java:283)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.renderSlow(BatchedEntryRendererManager.java:225)
	at me.shedaniel.rei.impl.client.gui.widget.BatchedEntryRendererManager.render(BatchedEntryRendererManager.java:125)
	at me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.method_25394(EntryListWidget.java:290)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:608)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.method_25394(ScreenOverlayImpl.java:506)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:341)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:54)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:63)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:89)
	at jdk.proxy3/jdk.proxy3.$Proxy142.render(Unknown Source)
	at net.minecraft.class_757.handler$zlf000$renderScreenPost(dev/architectury/mixin/fabric/client/MixinGameRenderer.java [architectury.mixins.json]:61)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: chiselsandbits:chiseledclay

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: chiseledclay
	Item Damage: 0
	Item NBT: {chiseledData:{}}
	Item Foil: false

-- Screen details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen

-- Renderer details --
Details:
	Renderer name: me.shedaniel.rei.impl.client.gui.widget.EntryListWidget.EntryListEntry
	Z level: 0
	Bounds: me.shedaniel.math.Rectangle@52ce33b4[height=18,width=18,x=544,y=82]
	Notice mark: 0
	Interactable: true
	Interactable favorites: true
	Highlight enabled: true
	Tooltip enabled: true
	Background enabled: false
	Entries count: 1

-- Current Rendering Entry --
Details:
	Renderer name: me.shedaniel.rei.impl.common.entry.TypedEntryStack
	Z level: 100
	Entry type: minecraft:item
	Is empty: false
	Entry identifier: chiselsandbits:chiseledclay

-- Entry Renderer --
Details:
	Entry definition class name: me.shedaniel.rei.plugin.client.entry.ItemEntryDefinition
	Item Type: chiseledclay
	Item Damage: 0
	Item NBT: {chiseledData:{}}
	Item Foil: false

-- Screen render details --
Details:
	Screen name: me.shedaniel.rei.impl.client.gui.screen.DefaultDisplayViewingScreen
	Mouse location: Scaled: (441, 331). Absolute: (1324.000000, 994.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['frikinjay'/1327, l='ClientLevel', x=964.70, y=94.00, z=-2875.20]]
	Chunk stats: 1024, 466
	Level dimension: minecraft:overworld
	Level spawn location: World: (1751,151,-2550), Section: (at 7,7,10 in 109,9,-160; chunk contains blocks 1744,-64,-2560 to 1759,319,-2545), Region: (3,-5; contains chunks 96,-160 to 127,-129, blocks 1536,-64,-2560 to 2047,319,-2049)
	Level time: 11454432 game time, 12215089 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
```

For any bug reports please provide the following details as well,
* MC Version: 1.18.1
* C&B Version: 1.2.66
* Do You have Optifine: No

**Comment by marchermans** [comment]
Update to them newest version
