### ISSUE TITLE
Using any fluid in a bucket on the Chiseld Bit Storage causes the game to crash

### ISSUE THREAD

**Issue by Shyclops** [ChiselsAndBits/Chisels-and-Bits#832]
```
> `[00:19:11] [Server thread/FATAL]: Error executing task on Server
> 
> java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60734_()" because "state" is null
> 
> 	at mod.chiselsandbits.chiseling.eligibility.EligibilityManager.lambda$analyse$1(EligibilityManager.java:59) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.chiseling.eligibility.EligibilityManager.analyse(EligibilityManager.java:58) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.api.chiseling.eligibility.IEligibilityManager.canBeChiseled(IEligibilityManager.java:28) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.item.bit.BitItemManager.create(BitItemManager.java:46) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.block.entities.BitStorageBlockEntity.m_8020_(BitStorageBlockEntity.java:299) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.block.entities.BitStorageBlockEntity.extractBits(BitStorageBlockEntity.java:244) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at mod.chiselsandbits.block.BitStorageBlock.m_6227_(BitStorageBlock.java:99) ~[ChiselsBits-forge-1.18.1-1.2.62.jar%2369!:1.2.62]
> 
> 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:335) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23244!:?]
> 
> 	at java.lang.Thread.run(Thread.java:833) [?:?]`
> 
```

For any bug reports please provide the following details as well,
*1.18.1
* 1.18.1-1.2.70-universal
* No optifine

**Comment by marchermans** [comment]
Fixed in the release which will be published in a couple of minutes.
