### ISSUE TITLE
Measuring Tape Causes Game/Server Crash

### ISSUE THREAD

**Issue by Kerbalino** [ChiselsAndBits/Chisels-and-Bits#843]
Hello!

Me and a couple of friends have started playing with a private modpack on a private server that includes Chisel & Bits.

When I tried using the Measuring Tape and switched from the white bits measurement to red distance measurements, the server crashed with the following error log. After starting it up again, entering the chunk where the measurements have been drawn, the server instantly crashes again. I've also managed to recreate the issue in singleplayer as well.

* MC Version: 1.18.1
* C&B Version: 1.2.73
* Do You have Optifine: No

Error log:

```
Time: 14/01/2022, 21:24
Description: Unexpected error

java.lang.IllegalStateException: Not filled all elements of the vertex
	at com.mojang.blaze3d.vertex.BufferBuilder.m_5752_(BufferBuilder.java:249) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:BufferBuilderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at mod.chiselsandbits.client.render.MeasurementRenderer.lambda$renderMeasurements$2(MeasurementRenderer.java:109) ~[ChiselsBits-forge-1.18.1-1.2.73-universal.jar%2367!:1.2.73] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:computing_frames,re:mixin}
	at mod.chiselsandbits.client.render.MeasurementRenderer.renderMeasurements(MeasurementRenderer.java:65) ~[ChiselsBits-forge-1.18.1-1.2.73-universal.jar%2367!:1.2.73] {re:classloading}
	at mod.chiselsandbits.client.logic.MeasurementsRenderHandler.renderMeasurements(MeasurementsRenderHandler.java:11) ~[ChiselsBits-forge-1.18.1-1.2.73-universal.jar%2367!:1.2.73] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.LevelRenderer.handler$zcf000$beforeDebugRender(LevelRenderer.java:4061) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1382) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1056) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:831) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:quartz.mixins.json:MinecraftShutdownMixin,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23115!:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.19.jar%2323!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%235!:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?] {}

```

**Comment by marchermans** [comment]
Fixed in latest
