### ISSUE TITLE
Server crashes when using measuring tape. making patterns not working

### ISSUE THREAD

**Issue by diamondryan599** [ChiselsAndBits/Chisels-and-Bits#852]
On a Shockbyte server with chisels and bits, fabric api, origns, and extra origins the measuring tape crashes the server right after trying to use it with a right click.

* MC Version:1.18.1 
* C&B Version:1-1 2.77 fabric
* Do You have Optifine: no

**Comment by diamondryan599** [comment]
this crash also happens when trying to open clipboard

**Comment by diamondryan599** [comment]
https://paste.shockbyte.com/edupamoticavuzetomuh
crash logs if needed

**Comment by marchermans** [comment]
Sorry but there is nothing in this crashlog that indicates that this is related to Chisels & Bits, but I will check it out later this week.

**Comment by diamondryan599** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 1/23/22, 10:35 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Fluid may not be flowing.
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:40)
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:65)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.makeVariant(FabricFluidManager.java:122)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.lambda$getFluidColor$2(FabricFluidManager.java:104)
	at mod.chiselsandbits.platforms.core.dist.DistExecutor.unsafeRunForDist(DistExecutor.java:150)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.getFluidColor(FabricFluidManager.java:103)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.buildFaceQuadLayers(FaceManager.java:96)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.lambda$getCachedFace$1(FaceManager.java:77)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.getCachedFace(FaceManager.java:73)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModel.generateFaces(ChiseledBlockBakedModel.java:287)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModel.<init>(ChiseledBlockBakedModel.java:198)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.lambda$get$2(ChiseledBlockBakedModelManager.java:93)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.get(ChiseledBlockBakedModelManager.java:90)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.get(ChiseledBlockBakedModelManager.java:51)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$1(DataAwareChiseledBlockBakedModel.java:82)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$4(DataAwareChiseledBlockBakedModel.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$6(DataAwareChiseledBlockBakedModel.java:92)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:71)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at net.minecraft.class_918.method_4026(class_918.java:346)
	at net.minecraft.class_918.method_36543(class_918.java:339)
	at net.minecraft.class_918.method_27951(class_918.java:335)
	at net.minecraft.class_465.method_2385(class_465.java:265)
	at net.minecraft.class_465.method_25394(class_465.java:123)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_481.method_25394(class_481.java:681)
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.transfer.fluid.FluidVariantImpl.of(FluidVariantImpl.java:40)
	at net.fabricmc.fabric.api.transfer.v1.fluid.FluidVariant.of(FluidVariant.java:65)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.makeVariant(FabricFluidManager.java:122)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.lambda$getFluidColor$2(FabricFluidManager.java:104)
	at mod.chiselsandbits.platforms.core.dist.DistExecutor.unsafeRunForDist(DistExecutor.java:150)
	at mod.chiselsandbits.fabric.platform.fluid.FabricFluidManager.getFluidColor(FabricFluidManager.java:103)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.buildFaceQuadLayers(FaceManager.java:96)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.lambda$getCachedFace$1(FaceManager.java:77)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.face.FaceManager.getCachedFace(FaceManager.java:73)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModel.generateFaces(ChiseledBlockBakedModel.java:287)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModel.<init>(ChiseledBlockBakedModel.java:198)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.lambda$get$2(ChiseledBlockBakedModelManager.java:93)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.get(ChiseledBlockBakedModelManager.java:90)
	at mod.chiselsandbits.client.model.baked.chiseled.ChiseledBlockBakedModelManager.get(ChiseledBlockBakedModelManager.java:51)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$1(DataAwareChiseledBlockBakedModel.java:82)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$4(DataAwareChiseledBlockBakedModel.java:86)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.lambda$resolve$6(DataAwareChiseledBlockBakedModel.java:92)
	at mod.chiselsandbits.utils.SimpleMaxSizedCache.get(SimpleMaxSizedCache.java:50)
	at mod.chiselsandbits.client.model.baked.chiseled.DataAwareChiseledBlockBakedModel.resolve(DataAwareChiseledBlockBakedModel.java:71)
	at mod.chiselsandbits.client.model.baked.base.BaseSmartModel$OverrideHelper.method_3495(BaseSmartModel.java:51)
	at net.minecraft.class_918.method_4019(class_918.java:258)
	at net.minecraft.class_918.method_4026(class_918.java:346)
	at net.minecraft.class_918.method_36543(class_918.java:339)
	at net.minecraft.class_918.method_27951(class_918.java:335)
	at net.minecraft.class_465.method_2385(class_465.java:265)
	at net.minecraft.class_465.method_25394(class_465.java:123)
	at net.minecraft.class_485.method_25394(class_485.java:29)
	at net.minecraft.class_481.method_25394(class_481.java:681)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (263, 97). Absolute: (791.000000, 291.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:875)
	at net.minecraft.class_310.method_1523(class_310.java:1117)
	at net.minecraft.class_310.method_1514(class_310.java:733)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['DiamondRyan599'/21, l='ClientLevel', x=2077.32, y=104.00, z=-4080.51]]
	Chunk stats: 729, 466
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,80,-128), Section: (at 0,0,0 in 1,5,-8; chunk contains blocks 16,-64,-128 to 31,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 19714033 game time, 6000 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, firenh-dream-smp-items-v2-1-e3600.zip, Fabric Mods, Origins Music Pack.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 637600280 bytes (608 MiB) / 1342177280 bytes (1280 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel(R) UHD Graphics 750
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x4c8a
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Graphics card #1 name: NVIDIA GeForce GTX 1650 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2187
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24760.46
	Virtual memory used (MB): 18015.02
	Swap memory total (MB): 8704.00
	Swap memory used (MB): 119.31
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		apoli: Apoli 2.2.2
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.0-alpha.1+21w37a
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0-alpha.1+21w37a
		chiselsandbits: Chisels & Bits 1.2.77
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.42
		extraorigins: Extra Origins 1.18-5
		fabric: Fabric API 0.45.2+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cd65
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.0+17be577f65
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a965
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d9565
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c665
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73d65
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.9+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378a65
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f1765
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cd65
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d9565
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f365
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cd65
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca33565
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d9565
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d9565
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.8+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d9565
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d9565
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.1+3b82842e65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.9+3ac43d9565
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1ac65
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.0+befed49e65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d9565
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d9565
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d765
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378a65
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d9565
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d9565
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d9565
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a765
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d9565
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.5+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.6+b4f4f6cd65
		fabricloader: Fabric Loader 0.12.12
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		minecraft: Minecraft 1.18.1
		origins: Origins 1.3.1
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		playerabilitylib: Pal 1.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		sit: Sit 1.18.1-16
	Launched Version: fabric-loader-0.12.12-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.41, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/firenh-dream-smp-items-v2-1-e3600.zip (incompatible), Fabric Mods, file/Origins Music Pack.zip
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz

**Comment by diamondryan599** [comment]
sorry i couldn't upload the text file but this is the crash log with the clipboard opening

**Comment by marchermans** [comment]
Fixed in 1.2.79
