### ISSUE TITLE
Tape Measure Brakes Servers

### ISSUE THREAD

**Issue by DrawnFromFlames** [ChiselsAndBits/Chisels-and-Bits#884]
* MC Version: 1.18.1
* C&B Version: 1.2.81
* Do You have Optifine: No

Tape Measure was used and now server continually crashes when joining

Tape measure was used and now after we can't play on our server
==========================

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2/27/22, 1:06 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/class_746
	at mod.chiselsandbits.item.MeasuringTapeItem.handleRightClickProcessing(MeasuringTapeItem.java:77)
	at mod.chiselsandbits.logic.RightClickInteractionHandler.rightClickOnItem(RightClickInteractionHandler.java:82)
	at mod.chiselsandbits.fabric.FabricChiselsAndBitsMod.lambda$setupEvents$5(FabricChiselsAndBitsMod.java:82)
	at net.fabricmc.fabric.api.event.player.UseItemCallback.lambda$static$0(UseItemCallback.java:42)
	at net.minecraft.class_3225.handler$zfo000$interactItem(class_3225.java:1596)
	at net.minecraft.class_3225.method_14256(class_3225.java)
	at net.minecraft.class_3244.method_12065(class_3244.java:1093)
	at net.minecraft.class_2886.method_12550(class_2886.java:25)
	at net.minecraft.class_2886.method_11054(class_2886.java:7)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:151)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162)
	at net.minecraft.class_1255.method_16075(class_1255.java:125)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756)
	at net.minecraft.class_1255.method_5383(class_1255.java:110)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:740)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (amd64) version 4.19.0-18-amd64
	Java Version: 17.0.1, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1712509216 bytes (1633 MiB) / 3124756480 bytes (2980 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 85858.84
	Virtual memory used (MB): 133344.19
	Swap memory total (MB): 21503.99
	Swap memory used (MB): 16037.38
	JVM Flags: 4 total; -Xmx4096M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	Fabric Mods: 
		apoli: Apoli 2.2.2
		autoconfig1u: Auto Config v1 Updated 3.3.1
		blue_endless_jankson: jankson 1.2.1
		calio: Calio 1.4.2
		cardinal-components-base: Cardinal Components API (base) 4.0.0-alpha.1+21w37a
		cardinal-components-entity: Cardinal Components API (entities) 4.0.0-alpha.1+21w37a
		chiselsandbits: Chisels & Bits 1.2.81
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		club_minnced_discord-webhooks: discord-webhooks 0.7.2
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.14.9
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		ec-core: Essential Commands Core 1.0.1-mc1.18.1
		essential_commands: Essential Commands 0.20.0-mc1.18.1
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.4+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.8+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.6+3ac43d9565
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.6+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.11+b4f4f6cd65
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.4+d7c144a865
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.12+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.14+713c266865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.8+d7c144a865
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.8+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.9+d7c144a865
		fabricloader: Fabric Loader 0.12.12
		fallingtree: FallingTree 3.2.1
		fdlink: Fabric <-> Discord Link 0.10.6
		fdlink_1_12_2: Fabric <-> Discord Link 0.10.6
		fdlink_1_15_2: Fabric <-> Discord Link 0.10.6
		fdlink_1_16: Fabric <-> Discord Link 0.10.6
		fdlink_1_6_4: Fabric <-> Discord Link 0.10.6
		fdlink_1_7_10: Fabric <-> Discord Link 0.10.6
		fdlink_1_8_9: Fabric <-> Discord Link 0.10.6
		fdlink_api: Fabric <-> Discord Link API 0.1.1
		fdlink_common: Fabric <-> Discord Link 0.10.6
		image2map: Image2Map 0.2.2
		inventorysorter: Inventory Sorter 1.8.4-1.18
		java: OpenJDK 64-Bit Server VM 17
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kyrptconfig: Kyrpt Config 1.3.4-1.18
		luckperms: LuckPerms 5.4.4
		minecraft: Minecraft 1.18.1
		naturescompass: Nature's Compass 1.18.1-2.0.2-fabric
		net_dv8tion_jda: JDA 4.4.0_352
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_json_json: json 20210307
		origins: Origins 1.3.1
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.3.0
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		seasons: Fabric Seasons 1.3-BETA+1.18
	Server Running: true
	Player Count: 1 / 80; [class_3222['Aquixtry'/88372, l='ServerLevel[world]', x=-15.03, y=65.00, z=39.48]]
	Data Packs: vanilla, Fabric Mods, file/micro
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by SirOMGitsYOU** [comment]
Any update on this? still impacting my server been over a month

**Comment by marchermans** [comment]
This should be fixed in the latest 1.18.2

**Comment by SirOMGitsYOU** [comment]
> This should be fixed in the latest 1.18.2

Would there be any plans to fix this on the 1.16.5 version aswell?

**Comment by marchermans** [comment]
Maybe if i have time.
Time is my current problem.

If anybody wants to Backport the fix hit me up, it should only be like 20 minutes of work.
But my focus is still om getting the latest version up to par with what it was before .

**Comment by HacoKavanah** [comment]
Description: Unexpected error

java.lang.UnsupportedOperationException
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
	at moriyashiine.extraorigins.client.event.RadialMenuEvents.lambda$init$0(RadialMenuEvents.java:38)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$4(ClientPlayConnectionEvents.java:64)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.invokeDisconnectEvent(ClientPlayNetworkAddon.java:148)
	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
	at net.minecraft.client.network.ClientPlayNetworkHandler.handler$edm002$handleDisconnection(ClientPlayNetworkHandler:2439)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onDisconnected(ClientPlayNetworkHandler)
	at net.minecraft.network.ClientConnection.handleDisconnection(ClientConnection:424)
	at net.minecraft.client.network.ClientPlayerInteractionManager.tick(ClientPlayerInteractionManager:276)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1709)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1091)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.clear(ImmutableCollections.java:149)
	at moriyashiine.extraorigins.client.event.RadialMenuEvents.lambda$init$0(RadialMenuEvents.java:38)
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayConnectionEvents.lambda$static$4(ClientPlayConnectionEvents.java:64)
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.invokeDisconnectEvent(ClientPlayNetworkAddon.java:148)
	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
	at net.minecraft.class_634.handler$edm002$handleDisconnection(class_634.java:2439)
	at net.minecraft.class_634.method_10839(class_634.java)
	at net.minecraft.class_2535.method_10768(class_2535.java:424)
	at net.minecraft.class_636.method_2927(class_636.java:276)

-- Affected level --
Details:
	All players: 3 total; [class_746['GGragsanJet'/174589, l='ClientLevel', x=-5892.57, y=73.00, z=2964.18], class_745['HacoKavanah'/154, l='ClientLevel', x=-5948.87, y=122.54, z=3019.28], class_745['ZannCoelz'/443363, l='ClientLevel', x=-5922.04, y=122.00, z=3021.42]]
	Chunk stats: 4096, 1225
	Level dimension: minecraft:overworld
	Level spawn location: World: (192,71,-192), Section: (at 0,7,0 in 12,4,-12; chunk contains blocks 192,-64,-192 to 207,319,-177), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 20459897 game time, 30753016 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

This crash occurs every time measuring tape is used, got ChiselsBits-fabric-1.18.2-1.2.87, fabric ver 0.14.5

**Comment by marchermans** [comment]
Fixed in 1.2.100
