### ISSUE TITLE
NullPointerException when placing Chiseld Bit Storage

### ISSUE THREAD

**Issue by TheGeka** [ChiselsAndBits/Chisels-and-Bits#912]
When placing the Chiseld Bit Storage the game crashes with a npe and every time you try to load into singleplayer or join multiplayer it crashes again while you are near it.

For any bug reports please provide the following details as well,
* MC Version: 1.18.2
* C&B Version: ChiselsBits-forge-1.18.2-1.2.87-universal
* Do You have Optifine: No using rubidium but the crash also happens when it's disabled
Crashlog:
```
java.lang.NullPointerException: Cannot invoke "mod.chiselsandbits.api.blockinformation.BlockInformation.serializeNBT()" because the return value of "mod.chiselsandbits.block.entities.BitStorageBlockEntity.getContainedBlockInformation()" is null
	at mod.chiselsandbits.block.BitStorageBlock.getTankDrop(BitStorageBlock.java:143) ~[ChiselsBits-forge-1.18.2-1.2.87-universal.jar%2366!/:1.2.87] {re:classloading}
	at mod.chiselsandbits.block.BitStorageBlock.m_7397_(BitStorageBlock.java:126) ~[ChiselsBits-forge-1.18.2-1.2.87-universal.jar%2366!/:1.2.87] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlock.getCloneItemStack(IForgeBlock.java:270) ~[forge-1.18.2-40.1.0-universal.jar%23127!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraftforge.common.extensions.IForgeBlockState.getCloneItemStack(IForgeBlockState.java:220) ~[forge-1.18.2-40.1.0-universal.jar%23127!/:?] {re:mixin,re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl.getPickedResult(BlockAccessorImpl.java:75) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at mcp.mobius.waila.impl.BlockAccessorImpl._getIcon(BlockAccessorImpl.java:87) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at mcp.mobius.waila.overlay.RayTracing.getIcon(RayTracing.java:162) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at mcp.mobius.waila.overlay.TooltipRenderer.<init>(TooltipRenderer.java:33) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:122) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at mcp.mobius.waila.WailaClient.onClientTick(WailaClient.java:133) ~[Jade-1.18.2-5.1.0.jar%2391!/:5.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_92_WailaClient_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2336!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostClientTick(ForgeEventFactory.java:907) ~[forge-1.18.2-40.1.0-universal.jar%23127!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1745) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1019) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:PickColorMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:ars_nouveau.mixins.json:light.ClientMixin,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23123!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.0.jar%2350!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
```
[crash-2022-05-05_10.58.21-client.txt](https://github.com/ChiselsAndBits/Chisels-and-Bits/files/8630037/crash-2022-05-05_10.58.21-client.txt)

**Comment by marchermans** [comment]
Hmm, I will see what I can reproduce.
